### PR TITLE
Change Snippet in transactedinstaller.cs

### PR DESCRIPTION
**Pull request by ghost**
## Summary

I changed snippet in transactedinstaller.cs
because I can't see all sample code in https://docs.microsoft.com/en-us/dotnet/api/system.configuration.install.transactedinstaller?view=netframework-4.8

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by BillWagner** [comment]
I'm waiting to review this, as I think it may have been fixed by the work @Thraka did in recovering a number of snipppets.

**Comment by Thraka** [comment]
@BillWagner The change @Asugakoisi is proposing actually just exposes more of the code, the entire sample (namespace declarations, the logging method, etc), which isn't many more lines. to what is published currently.

@Asugakoisi Is there somewhere you saw the snippet#2 being used? I can't find it anywhere. I think that `//snippet2` can be removed from the sample.

**Comment by Asugakoisi** [comment]
I'm sorry for forgetting checking these comments.

I removed `//snippet2`

**Comment by Thraka** [comment]
Thanks @Asugakoisi !!

**Pull request merged**
