### PR TITLE
Add ArgumentException and ANE to GetToolTipText

### PR DESCRIPTION
**Pull request by gewarren**
See https://github.com/dotnet/docs/pull/18049#issuecomment-618717246.

[Preview link](https://review.docs.microsoft.com/en-us/dotnet/api/system.windows.forms.tabcontrol.gettooltiptext?view=netcore-3.1&branch=pr-en-us-4178).

### CODE REVIEW

**Comment by gewarren** [comment]
@mairaw Did I version this exception correctly? Or is there a more sophisticated way?

`<exception cref="T:System.ArgumentException">.NET 5.0 and later only: The <paramref name="item" /> parameter is not of type <see cref="T:System.Windows.Forms.TabPage" />.</exception>`

**Comment by mairaw** [comment]
Looks good to me

**Comment by gewarren** [comment]
@RussKie Ping for review when you get a chance. I decided it probably makes more sense for me to update the exceptions in the API docs when I'm adding the breaking changes.

**Comment by gewarren** [comment]
Thanks for reviewing David!

**Pull request merged**
