### PR TITLE
Modified information about loss of precision for Single

### PR DESCRIPTION
**Pull request by rpetrusha**
## Modified information about loss of precision for Single

Fixes dotnet/docs#5401

/cc @mairaw @davidmatson

edit by @mairaw: fixed issue number

### CODE REVIEW

**Comment by mairaw** [comment]
Issue #5413 is about GetEmptyWebProxy. Maybe it's about another issue?

**Comment by mairaw** [comment]
I'm trying to parse all that the issue is describing and the changes being requested and I'm not exactly sure. 

For example:
> For example, I believe the bolded word should be Single instead of Double. 

It was already Single in the Single docs, no?

**Comment by davidmatson** [comment]
I originally reported the bug internally via email months ago; that part apparently has been fixed since then.

**Comment by mairaw** [comment]
Ah, all makes sense now! 😄

**Pull request merged**
