### PR TITLE
Add csproj file for String C# code samples

### PR DESCRIPTION
**Pull request by CorruptComputer**
## Summary
- Adds csproj file for String C# code samples
- Cleans up some of the code samples to be more readable

Still to do:
- String.IndexOfAny()
- String.Intern() 
- String.IsInterned()
- String.IsNullOrEmpty()
- String.Join()
- String.LastIndexOf()
- String.Length
- String.Normalize()
- String.Replace()
- String.ToCharArray()
- String.ToLower()
- String.ToUpper()

### CODE REVIEW

**Comment by gewarren** [comment]
@adegeo For the Snippets 5000 error message.

**Comment by gewarren** [comment]
> What I may end up doing to hopefully reduce errors and for easier review, is splitting this up into multiple small PR's. Would that be preferable over a large single PR?

Sorry that this went unanswered. Yes, multiple PRs would be easier to review. Also, all of the snippets in the VS_Snippets_CLR folder have now been reorganized in the way that Carlos suggested, and the top-level samples folder was removed, so your PR probably won't be quite as big once you pull in those changes.

**Comment by gewarren** [comment]
@CorruptComputer Do you still plan to work on this? I suggest we close this PR and you can add the readability changes on a new branch that's up to date with main (we made a lot of changes in the snippet folder structure).

**Comment by CorruptComputer** [comment]
@gewarren Sorry I've been quite busy lately and haven't found the time to come back to work on this. I'll just close this for now.

**Pull request closed without merging**
