### PR TITLE
Update results in the comment

### PR DESCRIPTION
**Pull request by yecril71pl**
This is what the code really prints.

## Summary

I updated the results in the comment as returned by v3.1.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=4743) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=4743) before we can accept your contribution.<br/><br/>:x: yecril71pl [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=4743)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-api-docs?pullRequest=4743) it.</sub>

**Comment by mairaw** [comment]
We'd have to make changes to the matching C++ and VB samples as well. But I'm thinking we should indicate these results are for .NET Core. Because running that on .NET Framework still produces the longer list of results.

**Comment by yecril71pl** [comment]
> We'd have to make changes to the matching C++ and VB samples as well. But I'm thinking we should indicate these results are for .NET Core. Because running that on .NET Framework still produces the longer list of results.

I assumed that .NET Framework lives in a separate branch.  It should.  Otherwise, and without having version-dependent text fragments, I have no idea how to handle this variety.  Saying _this is for Core and that is for Framework_ in plain text makes the documentation unreadable.

**Comment by tarekgh** [comment]
I don't think we need to change the results here. I'll try to look at the sample later and we may change it a little to use the CodePgaesEncodingProvider which will support returning the full list in .NET 5.0 too as it does on .NET Framework.

**Comment by yecril71pl** [comment]
> I don't think we need to change the results here. I'll try to look at the sample later and we may change it a little to use the CodePgaesEncodingProvider which will support returning the full list in .NET 5.0 too as it does on .NET Framework.

It is also possible to get all supported encodings by enumerating over all possible code page numbers.  Ugly but works.

**Comment by mairaw** [comment]
I'm also turning off .NET Interactive on that page for now since it's not really working
https://github.com/dotnet/dotnet-api-docs/pull/4839

> I assumed that .NET Framework lives in a separate branch. It should. Otherwise, and without having version-dependent text fragments, I have no idea how to handle this variety. Saying this is for Core and that is for Framework in plain text makes the documentation unreadable.

We have currently one source for all flavors. We might have conditional markup in the future but right now it's a single source for both Core and Framework.

**Comment by tarekgh** [comment]
I would suggest to keep the list as the example listed it with adding a comment like: 

If running on .NET Framework or running on .NET 5.0 with registering the codepages encoding provider `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);` you get a result similar to the following list: (keep the list deleted in this PR here).
if running on .Net Core versions, will get the list mentioned in the remark section https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netcore-3.1#remarks.

**Comment by carlossanlop** [comment]
@yecril71pl there has not been a response since September. I'll close the PR but feel free to reopen if you can address the suggestions.

**Comment by yecril71pl** [comment]
> @yecril71pl there has not been a response since September. I'll close the PR but feel free to reopen if you can address the suggestions.

I cannot address these suggestions.  User documentation should describe what actually happens.  It should not contain irrelevant documentation for other versions.

**Comment by carlossanlop** [comment]
@yecril71pl the API documentation in dotnet-api-docs is shared for all .NET versions (Framework or Core). So whatever information we show in MS Docs, needs to specify the output differences between versions (if any).

@tarekgh 's suggestion makes sense. You can always add two example files, one for Framework and one for Core, and we can show them both in the remarks section of the API that shows the example.

**Pull request closed without merging**
