### PR TITLE
Update source.cpp

### LINKED ISSUE #5353: Semaphore C# sample code not demonstrating usage clearly
Hi, in the C# code sample for Semaphore class usage, the main thread exits before the child threads complete execution. I suggest doing a Join() for all the child threads to keep the main thread alive and demonstrate the proper usage of semaphores. Perhaps by updating the code as follows, thanks.

    List<Thread> tl = new List<Thread>();
    for(int i = 1; i <= 5; i++)
    {
        Thread t = new Thread(new ParameterizedThreadStart(Worker));
    
        // Start the thread, passing the number.
        //
        t.Start(i);
        tl.Add(t);
    }
    
    // Wait for half a second, to allow all the
    // threads to start and to block on the semaphore.
    //
    Thread.Sleep(500);
    
    // The main thread starts out holding the entire
    // semaphore count. Calling Release(3) brings the 
    // semaphore count back to its maximum value, and
    // allows the waiting threads to enter the semaphore,
    // up to three at a time.
    //
    Console.WriteLine("Main thread calls Release(3).");
    _pool.Release(3);
    
    foreach (var t in tl)
    {
        t.Join();
    }
    
    Console.WriteLine("Main thread exits.");

_Originally posted by @captaindakkar in https://github.com/dotnet/dotnet-api-docs/issues/5320#issuecomment-782549337_

### PR DESCRIPTION
**Pull request by Rajakavitha1**
Updated the code snippet as suggested in https://github.com/dotnet/dotnet-api-docs/issues/5353

## Summary

Describe your changes here.

Fixes #5353

### CODE REVIEW

**Comment by carlossanlop** [comment]
Ping @kouvel can you please review?

**Comment by gewarren** [comment]
@kouvel Could you review this small change?

If it looks good, then the conflict will have to be resolved (the top-level samples folder was delete and everything under it moved up a level).

**Comment by kouvel** [comment]
It looks like the C++/CLI version of the sample has been fixed and there are three more variants of the sample, C#, VB, and F#. The change looks good to me, it would be nice to fix all of them. @Rajakavitha1, would you be willing to do that?

**Comment by kouvel** [comment]
Granted, I also haven't verified that this builds and works, @Rajakavitha1 have you verified that it works?

**Comment by gewarren** [comment]
Closing due to inactivity and conflict.

**Pull request closed without merging**
