### PR TITLE
CI Update - mdoc 5.7.0.1

### PR DESCRIPTION
**Pull request by dend**
This addresses .NET blocker issues.

### CODE REVIEW

**Comment by dend** [comment]
@mairaw @BillWagner @rpetrusha please review.

**Comment by mairaw** [comment]
F# was not showing up as an option in the version selector so my last change should enable that

**Comment by mairaw** [comment]
hopefully my change will also fix the triple name that is happening
https://review.docs.microsoft.com/en-us/dotnet/api/system.string?view=netframework-4.7.2&branch=pr-en-us-293

image

**Comment by dend** [comment]
@mairaw looks like your change did the trick!

**Pull request merged**
