### PR TITLE
Changed String to string. IDE0049

### PR DESCRIPTION
**Pull request by muhammadzakriashahid**
## Summary

Describe your changes here.
i change the String type to string. Because of the rule ID IDE0049 Use language keywords instead of framework type names for type references.
Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by BillWagner** [comment]
tag @gewarren 

I know that our general guideline is to use `string` vs. `String`. Do you want to follow that same guideline for the `System.String` APIs?

**Comment by gewarren** [comment]
> tag @gewarren
> 
> I know that our general guideline is to use `string` vs. `String`. Do you want to follow that same guideline for the `System.String` APIs?

Yes, I don't see why not.

**Review by gewarren — APPROVED** [review]

**Comment by gewarren** [comment]
@muhammadzakriashahid Can you add a project file similar to https://github.com/dotnet/dotnet-api-docs/blob/main/snippets/csharp/System/Math/E/Project.csproj but for .net8.0 in the directory that contains the snippet? This is a newer requirement that we enforce whenever a code snippet is modified so we can ensure it compiles.

**Comment by muhammadzakriashahid** [comment]
@dotnet-policy-service agree

**Comment by muhammadzakriashahid** [comment]
haven't heard from you guys

**Review by gewarren — APPROVED** [review]

**Comment by gewarren** [comment]
Thanks @muhammadzakriashahid

**Pull request merged**
