### PR TITLE
standardize sample location

### PR DESCRIPTION
**Pull request by mairaw**
It's a bit confusing two have to top-level folders for snippets. Moving the Rune snippets to where other examples are.

image

### CODE REVIEW

**Comment by BillWagner** [comment]
I'll defer to @tdykstra here.

**Comment by tdykstra** [comment]
/samples/snippets was only put there for the en masse transfer of all snippet files.  The intended destination that we'll be moving to gradually is /snippets

**Comment by tdykstra** [comment]
From #17297

>For API reference, the repository will have a snippets folder at the root of the repository. Each project will be in a sub-folder that matches the sub-folder path for the associated XML file where the snippet is included. For example, snippets used in ~/xml/System.Collections.Generic/List`1.xml would be stored in ~/snippets/System.Collections.Generic/List`1 folder.

**Comment by mairaw** [comment]
Ok, so closing this. It just looks weird now. 😄

**Pull request closed without merging**
