### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by gewarren**
Added the following assemblies to the dotnet-plat-ext-5.0 folder:

Microsoft.Extensions.Configuration.KeyPerFile.dll
Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll
Microsoft.Extensions.Diagnostics.HealthChecks.dll
Microsoft.Extensions.FileProviders.Embedded.dll
Microsoft.Extensions.Localization.Abstractions.dll
Microsoft.Extensions.Localization.dll
Microsoft.Extensions.ObjectPool.dll
Microsoft.Extensions.WebEncoders.dll
Microsoft.Win32.Registry.dll
System.Security.AccessControl.dll
System.Security.Cryptography.Cng.dll
System.Security.Principal.Windows.dll

### CODE REVIEW

**Comment by gewarren** [comment]
There are a few constructors that look like they were removed after .NET Core 3.1 that use internal types as parameters, for example, [ResourceManagerStringLocalizer](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.resourcemanagerstringlocalizer.-ctor?view=dotnet-plat-ext-3.1&branch=pr-en-us-5185#Microsoft_Extensions_Localization_ResourceManagerStringLocalizer__ctor_System_Resources_ResourceManager_Microsoft_Extensions_Localization_Internal_IResourceStringProvider_System_String_Microsoft_Extensions_Localization_IResourceNamesCache_Microsoft_Extensions_Logging_ILogger_). Is it okay to have those in there? They are generating xref not found warnings, so we'll never get a clean build.

**Comment by BillWagner** [comment]
@gewarren 

We should add the missing class declarations to the [missing APIs](https://github.com/dotnet/dotnet-api-docs/blob/master/_zip/missingapi.yml) config file. Then the xrefs won't generate links, but will be codefenced. This also removes the warnings.

**Comment by gewarren** [comment]
@BillWagner Can you approve this PR?

**Review by BillWagner — APPROVED** [review]
Thanks for adding the additional missing APIs.

This LGTM, and you can :shipit: when ready.

**Pull request merged**
