### PR TITLE
System.DateTime F# snippets

### PR DESCRIPTION
**Pull request by albert-du**
Adds F# snippets for DateTime

### CODE REVIEW

**Comment by albert-du** [comment]
@dsyme @baronfel Could you review?

**Comment by BillWagner** [comment]
Adding @dsyme for review.

I reviewed much of the code, and everything looks good to me. I don't think it needs a close review, but I'd appreciate a look at some samples and checking for recommended F# idioms.

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
Amazing work!!!

**Review by BillWagner — APPROVED** [review]
LGTM as well. Again, thanks @albert-du

**Pull request merged**
