### PR TITLE
IgnoreNullValues isn't for deserialization

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes https://github.com/dotnet/docs/issues/23450

### CODE REVIEW

**Review by gewarren — APPROVED** [review]
Should you also add a remark in the remarks section that it does not apply to deserialization?

**Comment by tdykstra** [comment]
@gewarren Thanks for the review!

**Comment by layomia** [comment]
Actually, `IgnoreNullValues` _is_ honored when deserializing. We did this for compat with `Newtonsoft.Json` ([NullValueHandling](https://www.newtonsoft.com/json/help/html/NullValueHandlingIgnore.htm)) in v1 (.NET Core 3.x), but ended up obsoleting it after introducing `DefaultIgnoreCondition` in .NET 5.

`DefaultIgnoreCondition` (currently) only applies to serialization. When designing the new option, we couldn't think of a good reason to ignore `null` values in JSON payloads when reading. Most `Newtonsoft.Json` users don't even know that `NullValueHandling` is honored when deserializing. We decided not to carry over the "mistake" we made with `IgnoreNullValues`.

**Comment by layomia** [comment]
cc @tdykstra - https://github.com/dotnet/dotnet-api-docs/pull/5470#issuecomment-806306430.

**Pull request merged**
