### PR TITLE
bug fixes and improvements to Enumerable APIs

### LINKED ISSUE #795: Need add remark for Except method with IEquailityComparer
First Except method (without IEqualityComparer) have important remark about that "The set difference of two sets is defined as the members of the first set that do not appear in the second set".

But second Except method (with IEqualityComparer) doesn't have such a remark. Due to you might think that this method return difference of two sets is defined as the members of the first set that do not appear in the second set and the members of the second set that do not appear in the first set.

Though these methods works the same way.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a5fb66fb-9a33-2550-2783-7ce2a4760219
* Version Independent ID: 2e80b927-7888-1fc8-7db9-d052b33ac87a
* Content: [Enumerable.Except Method (System.Linq)](https://docs.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.except?view=netframework-4.7.1)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

### LINKED ISSUE #848: Also see Intersect which does the opposite.
Also see Intersect which does the opposite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5fb66fb-9a33-2550-2783-7ce2a4760219
* Version Independent ID: 2e80b927-7888-1fc8-7db9-d052b33ac87a
* Content: [Enumerable.Except Method (System.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?view=netframework-4.7.2)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

### LINKED ISSUE #849: Also see Except which does the opposite.
Also see Except which does the opposite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722d6038-c75b-426d-5344-c9b91e525453
* Version Independent ID: 32b9aa16-56a7-4c9a-f71a-b594a2df9e61
* Content: [Enumerable.Intersect Method (System.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.intersect?view=netframework-4.7.2)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

### LINKED ISSUE #1211: Example does not produce correct output
In the 1st example using the ProductA type the result is not:
orange 4
lemon 12

It is:
apple 9
orange 4
lemon 12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5fb66fb-9a33-2550-2783-7ce2a4760219
* Version Independent ID: 2e80b927-7888-1fc8-7db9-d052b33ac87a
* Content: [Enumerable.Except Method (System.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?redirectedfrom=MSDN&view=netframework-4.7.2#System_Linq_Enumerable_Except__1_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___0__)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

### LINKED ISSUE #1215: If first list contains two simillar elements and even though the second list doesnt contain it, 'except' returns only one element of the first list
If first list contains two simillar elements and even though the second list doesnt contain it, 'except' returns only one element of the first list 

See https://dotnetfiddle.net/tAjsEe

edit by @mairaw: cleaned up the issue and added the docs info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5fb66fb-9a33-2550-2783-7ce2a4760219
* Version Independent ID: 2e80b927-7888-1fc8-7db9-d052b33ac87a
* Content: [Enumerable.Except Method (System.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?view=netframework-4.7.2#System_Linq_Enumerable_Except__1_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___0__)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #849 
Fixes #848
Fixes #795 
Fixes #1215 
Fixes #1211 
Contributes to https://github.com/dotnet/docs/issues/2037
Contributes to #918

Related PR: https://github.com/dotnet/samples/pull/484

What did I do in this PR?
- Created a new note for interactive since previous ones assumed all samples on the page were interactive and added interactive to the Except, Intersect and Union samples that were in a single snippet. Others can be done if we change how the snippet files are structured later.
- Replaced MSDN links with docs links when possible 
- Added VB counterparts where missing
- Fixed remarks for Intersect, Except, Union and SequenceEqual. When using the default comparer, the instructions and the samples were wrong and didn't work.
- Moved some notes that were inside the remarks of one of the Except overloads to the main Remarks section and added clarification that only returns unique elements.

Internal review links:
- https://review.docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?view=netframework-4.7.2&branch=pr-en-us-1217
- https://review.docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.intersect?view=netframework-4.7.2&branch=pr-en-us-1217
- https://review.docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.union?view=netframework-4.7.2&branch=pr-en-us-1217

### CODE REVIEW

**Comment by mairaw** [comment]
@cston, @333fred can you please take a look at these changes to some of the Enumerable API docs?

**Comment by cston** [comment]
>  The default equality comparer, <xref:System.Collections.Generic.EqualityComparer%601.Default%2A>, is used to compare values of the types, which in turn uses the implementation of <xref:System.IEquatable%601.Equals%2A?displayProperty=nameWithType> method in the class that implements the <xref:System.IEquatable%601> generic interface. To compare a custom data type, you need to implement the `IEquatable<T>` interface and override the <xref:System.Object.GetHashCode%2A> and <xref:System.Object.Equals%2A> methods in the custom type.

Should this be "implement the `IEquatable<T>` interface _or_ override `System.Object.GetHashCode` and `System.Object.Equals`"? (I thought `EqualityComparer<T>.Default` will use `IEquatable<T>` if implemented, otherwise it will use `System.Object.Equals`.)

---
Refers to: xml/System.Linq/Enumerable.xml:2877 in 8e04327. [](commit_id = 8e04327d31be62899795c348ad4aa64799ff8bed, deletion_comment = False)

**Comment by cston** [comment]
>  The default equality comparer, <xref:System.Collections.Generic.EqualityComparer%601.Default%2A>, is used to compare values of the types, which in turn uses the implementation of <xref:System.IEquatable%601.Equals%2A?displayProperty=nameWithType> method in the class that implements the <xref:System.IEquatable%601> generic interface. To compare a custom data type, you need to implement the `IEquatable<T>` interface and override the <xref:System.Object.GetHashCode%2A> and <xref:System.Object.Equals%2A> methods in the custom type.

Actually, it looks like `GetHashCode` is required regardless of whether the type implements `IEquatable<T>`. So the comment could be something like "override `System.Object.GetHashCode` and `System.Object.Equals` and optionally implement `IEquatable<T>`"

---
In reply to: [442934528](https://github.com/dotnet/dotnet-api-docs/pull/1217#issuecomment-442934528) [](ancestors = 442934528)

---
Refers to: xml/System.Linq/Enumerable.xml:2877 in 8e04327. [](commit_id = 8e04327d31be62899795c348ad4aa64799ff8bed, deletion_comment = False)

**Comment by mairaw** [comment]
Sorry for only going back to this now. @cston I think implement is the right term. This is also used in the C# spec: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/interfaces

**Pull request merged**
