### PR TITLE
Replaced FwLink and changed link format

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Relates to https://github.com/dotnet/docs/issues/3391

This single fwlink was in this repo nearly 2000 times. 🙂 It was repeated in the same phrase, so I created an include file instead.

I wasn't totally sure how to do this though, so some questions:
- Is my include file ok with a relative link in, when it's used in places like the `<summary>` section? I see the current syntax doesn't render correctly in the API lookup

image

- I wasn't sure what the text in the square brackets of the `[!INCLUDE[asp mobile homepage](../includes/asp-mobile-md.md)]` was meant to be? Is "asp mobile homepage" ok?

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
Again, this is a big PR sorry - but I didn't see much sense in splitting it up. Let me know if I should do!

**Comment by mairaw** [comment]
You can see [here](https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.0) what happens when you use an include:

image

**Comment by ChrisMaddock** [comment]
Oh! 😞 I thought I was being clever!

That lookup doesn't seem to support markdown links at all. Would writing it as plaintext be better? Or maybe we should just cut the text altogether - I'm not sure how much value it's adding?

image

**Comment by mairaw** [comment]
No, it doesn't. 😢 

You can see a PR that solves this issue [here](https://github.com/dotnet/dotnet-api-docs/pull/14/files). 

So try changing them like this:
`<see href="https://docs.microsoft.com/aspnet/mobile/overview">www.asp.net/mobile</see>`.

Without https://docs.microsoft.com/ might work but because this content also goes into IntelliSense I kept the domain in there until I had time to test the whole workflow.

**Comment by ChrisMaddock** [comment]
Great - thanks @mairaw - updated!

**Pull request merged**
