### PR TITLE
Fill in some missing docs for SqlClient

### PR DESCRIPTION
**Pull request by roji**
Copied from [DbDataReader.Dispose(bool)](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.dispose?view=netframework-4.8#System_Data_Common_DbDataReader_Dispose_System_Boolean_) and [IDbColumnSchemaGenerator.GetColumnSchema](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.idbcolumnschemagenerator.getcolumnschema?view=netcore-3.0#System_Data_Common_IDbColumnSchemaGenerator_GetColumnSchema).

/cc @carlossanlop @mairaw @cheenamalhotra @David-Engel @ajcvickers

### CODE REVIEW

**Comment by BillWagner** [comment]
closing & reopening to start a new build.

**Comment by BillWagner** [comment]
I can't spot what's causing the build error.

@mairaw Do you see it?

**Comment by mairaw** [comment]
Made a change. Hopefully it’ll pass now.

**Comment by mairaw** [comment]
Weird error in the build report. Trying again.

**Pull request merged**
