### PR TITLE
Clarify that ZipArchive supports ZIP64.

### PR DESCRIPTION
**Pull request by ericmutta**
I spent a great deal of time trying to figure out whether the `ZipArchive` class supports the [ZIP64 format](https://en.wikipedia.org/wiki/ZIP_(file_format)#ZIP64) and could thus create archives that are larger than 4GB in size.  I don't see any official documentation that says it can, even though the code shows that [ZIP64 is in fact supported](https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs#L464), so I added a sentence to the summary of the `ZipArchive` class.

### CODE REVIEW

**Comment by ericmutta** [comment]
Any word on this?

**Comment by carlossanlop** [comment]
Thank you for your patience, and apologies for the delay.

I agree with you, we should have some clarification about zip64 somewhere in our zip docs. 

We used to have another issue asking about zip64 but I closed it since there was no request to modify the docs.  In hindsight, I should've proposed the docs improvement. 
 https://github.com/dotnet/dotnet-api-docs/issues/834#issuecomment-425173006

I think eventually we should also mention the conditions required for zip64 to work:  We support zips larger than 4gb when they're encoded in supported methods and decoded in Read Mode.  But I can add that info in a separate PR after I confirm all the info we need to mention.

Can you please move your new text to the remarks, please? The summary does not seem the appropriate location.

**Comment by ericmutta** [comment]
Hi @carlossanlop many thanks for getting back to me!

As per your suggestion, I have removed the text from the summary and added a short sentence to the remarks which simply says:

> **Zip packages larger than 4GB are supported.**

I believe that covers the two questions I had personally when looking into this:

1. Can I _create_ a zip archive larger than 4GB?
2. Can I _read_ a zip archive larger than 4GB?

One final question a person might have is: **Can I _add/remove_ entries in an existing archive that is larger than 4GB?** This is not too important in my use case but if the answer is known, I will be happy to make further edits to the remarks to add the info :+1:

**Comment by BillWagner** [comment]
Ping @carlossanlop to answer above question.

**Comment by ericmutta** [comment]
Closing this as it doesn't look like a priority to the docs team (it's been _two months_) :disappointed:

**Pull request closed without merging**
