### PR TITLE
Add OperationCanceledException exceptions automatically

### PR DESCRIPTION
**Pull request by gewarren**
Replaces #8776, which had too many conflicts.

### CODE REVIEW

**Comment by gewarren** [comment]
@stephentoub If the methods actually throw a TaskCanceledException, I guess it's still okay to catch OperationCanceledException when you await?

**Comment by stephentoub** [comment]
> @stephentoub If the methods actually throw a TaskCanceledException, I guess it's still okay to catch OperationCanceledException when you await?

Yes, in fact we want folks to catch OperationCanceledException and not TaskCanceledException. From my perspective, our introducing TaskCanceledException was a well-intentioned mistake. The idea was that it would be an OperationCanceledException that would carry a little more information (the Task that was canceled) if necessary, but that additional information is basically never useful or needed, and it's often not even possible to provide, yet because APIs were throwing it, developers started writing catch blocks for it, which then made it a breaking change for the implementation throwing it to be tweaked in such a way that the base OperationCanceledException was being thrown. We should probably introduce an analyzer to warn people off from catching TaskCanceledException, and maybe even obsolete it.

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

Let's :shipit:

**Comment by BillWagner** [comment]
Based on @stephentoub 's comment, I checked our conceptual and samples repos. 

In conceptual docs, I found 138 instances of `TaskCanceledException`. In our samples, I found 101 instances. Should we update the relevant `catch` clauses, and the text describing them to catch `OperationCanceledException` instead?

**Comment by gewarren** [comment]
> In conceptual docs, I found 138 instances of `TaskCanceledException`. In our samples, I found 101 instances. Should we update the relevant `catch` clauses, and the text describing them to catch `OperationCanceledException` instead?

@BillWagner I'd say yes!

**Comment by stephentoub** [comment]
Yes, please and thank you.

**Pull request merged**
