### PR TITLE
CI Update - Introduce "package-provided" monikers

### LINKED ISSUE #10012: Docs show some APIs added in .NET 9 preview as available in .NET 8
image

This API is only available for 9. Same happens for `IndentCharacter` and `IndentSize`. Not sure if it's a bug in the xml content or in the rendering tool.

cc @gewarren 

---
[Associated WorkItem - 335641](https://dev.azure.com/msft-skilling/Content/_workitems/edit/335641)

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #10012 

Build.Reason:Manual by Genevieve Warren
Build.Url:https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=473983&view=results
 source_repo.branch:pp-monikers
 source_repo.url:https://apidrop.visualstudio.com/_git/binaries

## Summary

- Expand down-level package APIs into "package-provided" monikers for .NET Framework 4.7-4.8.1, .NET Standard 2.0-2.1, .NET 6-9. (I didn't add .NET Framework 4.6.2 because I [ran into errors in mdoc](https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=473549&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102&l=58935).)
- Also adds Microsoft.Extensions.AI and Microsoft.IO.Redist packages.

## Preview

Will be very hard to actually look at the diffs. Might have to make do with just looking at the previews.

[FrozenDictionary<TKey,TValue> Class (System.Collections.Frozen) | Microsoft Learn](https://review.learn.microsoft.com/en-us/dotnet/api/system.collections.frozen.frozendictionary-2?view=net-9.0&branch=pr-en-us-10646#applies-to)

image

### CODE REVIEW

**Comment by YoshiRulz** [comment]
THANK YOU SO MUCH, this is huge for those of us still targeting .NET Standard 2.0.

**Comment by ManickaP** [comment]
Is it intentional that once I get into this "(package-provided)" docs, I cannot look up and quickly jump to APIs from in-box libraries:
image

Yes, I can do global search, but that's much less user friendly than it used to be.

**Comment by gewarren** [comment]
> Is it intentional that once I get into this "(package-provided)" docs, I cannot look up and quickly jump to APIs from in-box libraries: 

It's an unfortunate side effect, yes, because it only searches within the selected moniker. Also if you go to the System.Net.Http namespace page for each moniker, it only shows the types that are in that moniker, not the entire namespace:

- https://learn.microsoft.com/en-us/dotnet/api/system.net.http?view=net-8.0 
- https://learn.microsoft.com/en-us/dotnet/api/system.net.http?view=net-8.0-pp

@nickwalkmsft @mtrilbybassett @huangmin-ms Any suggestions on how we could provide a better experience here? Would it be possible to combine, say, the .NET 8 and .NET 8 (package-provided) monikers into a single namespace page?

**Comment by carlossanlop** [comment]
This is awesome. cc @ericstj @ViktorHofer

**Pull request merged**
