### PR TITLE
Add detail on default value for asp.net hosted applications

### PR DESCRIPTION
**Pull request by laedit**
## Summary

Add detail on default value for asp.net hosted applications.

Fixes dotnet/docs#5389

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @laedit for jumping on the issue. @karelz @davidsh do you want to double check this change?

**Comment by karelz** [comment]
Looks good - the info is already mentioned later on a Note on the same page. Do we want to remove that part? https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit?redirectedfrom=MSDN&view=netframework-4.7.2#System_Net_ServicePointManager_DefaultConnectionLimit

**Comment by rpetrusha** [comment]
@laedit, could you remove "When used in the server environment (ASP.NET) DefaultConnectionLimit defaults to higher number of connections, which is 10." from the note later in the DefaultConnectionLimit documentation?

**Comment by laedit** [comment]
@rpetrusha done, is that ok for you?

**Pull request merged**
