### PR TITLE
Filter out JS interop APIs for compiler

### PR DESCRIPTION
**Pull request by gewarren**
See https://github.com/dotnet/dotnet-api-docs/pull/8390#issuecomment-1248423348.

Filtering reference: https://review.docs.microsoft.com/en-us/help/onboard/admin/reference/dotnet/filtering-apis?branch=main#filter-apis-with-certain-attributes

### CODE REVIEW

**Comment by gewarren** [comment]
@pavelsavara Should the following types also be non-editor browsable?

[JSMarshalerArgument.ArgumentToJSCallback<T> Delegate](https://review.docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.javascript.jsmarshalerargument.argumenttojscallback-1?view=net-7.0&branch=pr-en-us-8392)
[JSMarshalerArgument.ArgumentToManagedCallback<T> Delegate](https://review.docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.javascript.jsmarshalerargument.argumenttomanagedcallback-1?view=net-7.0&branch=pr-en-us-8392)

**Comment by pavelsavara** [comment]
> ArgumentToJSCallback Delegate

Yes, I thought they are hidden by the fact they are nested type in `JSMarshalerArgument` which is `EditorBrowsableState.Never`.
So we need to fix it on the API ?

**Review by BillWagner — APPROVED** [review]
Thanks again @gewarren 

This LGTM. Let's :shipit: once you and @pavelsavara are happy.

**Comment by gewarren** [comment]
> > ArgumentToJSCallback Delegate
> 
> Yes, I thought they are hidden by the fact they are nested type in `JSMarshalerArgument` which is `EditorBrowsableState.Never`. So we need to fix it on the API ?

@pavelsavara Yes I tested this and IntelliSense still shows the nested type even if the parent type is `EditorBrowsableState.Never`. Do you want to submit a PR to hide the nested types?

**Comment by pavelsavara** [comment]
> @pavelsavara Yes I tested this and IntelliSense still shows the nested type even if the parent type is `EditorBrowsableState.Never`. Do you want to submit a PR to hide the nested types?

Thanks for checking, I created https://github.com/dotnet/runtime/pull/75800 to address it on main and will ask for backport.

**Review by pavelsavara — APPROVED** [review]

**Comment by gewarren** [comment]
The warnings will go away once we import the RC 2 APIs, so merging this now.

**Pull request merged**
