### PR TITLE
GlobalAssemblyCache updates

### PR DESCRIPTION
**Pull request by gewarren**
Contributes to dotnet/docs#20993.

### CODE REVIEW

**Comment by gewarren** [comment]
@GrabYourPitchforks This should be a quick review. Could you take a look?

**Comment by gewarren** [comment]
@carlossanlop Who owns System.Reflection now?

**Comment by eiriktsarpalis** [comment]
@buyaa-n @joperezr @krwq @steveharter could you take a look?

**Comment by gewarren** [comment]
Ping again for review.

**Review by GrabYourPitchforks — APPROVED** [review]

**Pull request merged**
