### PR TITLE
Fix Expression.Lambda summaries

### PR DESCRIPTION
**Pull request by nxtn**
Delegate type known/unknown.

### CODE REVIEW

**Comment by NextTurn** [comment]
I assume that it's a general guideline for all overloaded methods?

**Comment by rpetrusha** [comment]
Yes, it is, @NextTurn. Admittedly, you can find many, many instances in the docs where method descriptions are all the same. But that's not by design; the intent of the overload list at the top of the page is to help someone easily identify the method they need to call. If they're not disambiguated, that's very difficult.

**Comment by NextTurn** [comment]
It would be non-trivial amount of work to fix so many.

**Comment by rpetrusha** [comment]
Yes, it would be, @NextTurn. We've been trying to fix them on a one-by-one basis as we've touched the overloads.

**Comment by NextTurn** [comment]
I've made parallel changes in `Expression.Lambda<TDelegate>` overloads. This is ready for review, @rpetrusha.

**Comment by rpetrusha** [comment]
Build status not reported in OPS build report. Closing and reopening to begin new build.

Thank you so much for doing this extra work, @NextTurn. I'll review it once the build completes.

**Comment by rpetrusha** [comment]
Thank you so much, @NextTurn. You've done an excellent job of disambiguating these overloads. I'll merge your PR now.

**Pull request merged**
