### PR TITLE
CI Update - .NET 8 Preview 3

### PR DESCRIPTION
**Pull request by gewarren**
Build.Reason:Manual by Genevieve Warren
 Build.Url:https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=356306&view=results
 source_repo.branch:net8-pre3
 source_repo.url:https://apidrop.visualstudio.com/_git/binaries

Fixes dotnet/docs#8905

### CODE REVIEW

**Comment by carlossanlop** [comment]
Where is `System.Windows.Forms.ComboBox.ObjectCollection.Entry`?

It's being referenced in multiple locations of this file: [xml/System.Windows.Forms/ComboBox%2BObjectCollection.xml#L8-L10](https://github.com/dotnet/dotnet-api-docs/blob/b6a4438ace888c9b08263cbce404a1020f20e9e0/xml/System.Windows.Forms/ComboBox%2BObjectCollection.xml#L8-L10), but I can't find the type `ObjectCollection` by itself. I can only find `ComboBox+ObjectCollection`, which is that same file.

**Review by carlossanlop — APPROVED** [review]
Only left one question. It could very well be a bug in mdoc and not something actionable here. Otherwise, looks good.

**Comment by gewarren** [comment]
> Where is `System.Windows.Forms.ComboBox.ObjectCollection.Entry`?
> 
> It's being referenced in multiple locations of this file: [xml/System.Windows.Forms/ComboBox%2BObjectCollection.xml#L8-L10](https://github.com/dotnet/dotnet-api-docs/blob/b6a4438ace888c9b08263cbce404a1020f20e9e0/xml/System.Windows.Forms/ComboBox%2BObjectCollection.xml#L8-L10), but I can't find the type `ObjectCollection` by itself. I can only find `ComboBox+ObjectCollection`, which is that same file.

It's an internal type: https://github.com/dotnet/winforms/blob/d46ad2e8dc76248739d9ae22b28b399a6a6b299e/src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.Entry.cs.

@merriemcgaw FYI that ComboBox.ObjectCollection uses an internal type for parameters of a public method: https://github.com/dotnet/dotnet-api-docs/blob/b6a4438ace888c9b08263cbce404a1020f20e9e0/xml/System.Windows.Forms/ComboBox%2BObjectCollection.xml#L664-L705. Is that by design?

**Comment by merriemcgaw** [comment]
@dreddy-work / @JeremyKuhne does the issue with ComboBox.ObjectCollection ring a bell?

**Comment by dreddy-work** [comment]
This was added in .NET 6.0 preview 1. I am not certain on the impact of this.

**Pull request merged**
