### PR TITLE
specify what the Multiply(Vector3, Vector3) operator overload does

### PR DESCRIPTION
**Pull request by Double-A-92**
The Multiply(Vector3, Vector3) operator overload seems to multiply the two given Vector3s element-wise. Added this information to the docs so we don't have to guess and try it out anymore. 👍

### CODE REVIEW

**Comment by BillWagner** [comment]
/cc @tannergooding @VicktorHofer

These changes LGTM. Can you check that this is how the `Vector3.Multiply` method should be described?

**Comment by tannergooding** [comment]
@Double-A-92, would you also be willing to fix-up the documentation for `Vector2` and `Vector4`, as well as the `op_Multiply(Vector, Vector)` methods for each?

It would be nice to get them all fixed up at once, if possible.

**Comment by Double-A-92** [comment]
@tannergooding Sure, I could do that. Do you think the text / description is good as it is in this PR?

**Comment by BillWagner** [comment]
@Double-A-92 

> Do you think the text / description is good as it is in this PR?

I would say, yes, the description is fine. Thank you for adding the other related classes as well.

**Comment by Double-A-92** [comment]
@tannergooding  @BillWagner Done.
I found an already existing description for that in the Vector (without number), and used that for all of the others.

Just out of curiosity... What happens to the in-code documentation comments? Will they get automatically updated based on this repository?

**Comment by BillWagner** [comment]
@Double-A-92 

> What happens to the in-code documentation comments? Will they get automatically updated based on this repository?

It depends on the repository. In the case of the APIs that have multiple implementations (.NET Core, .NET Framework), the XML files were exported once, and that's now considered our source of truth. In many other repositories, the /// comments are the source of truth, and we don't edit the exported XML.  The tools we use are being updated to make this more clear and easier to work with.

Usually, if the docs repo is open for public contribution, the XML files in the docs repo are the source of truth. The README.MD or CONTRIBUTING.MD should also say. If you find any that aren't explicit, that's an issue we should fix.

**Pull request merged**
