### PR TITLE
Enable Try.NET with the new syntax

### PR DESCRIPTION
**Pull request by mairaw**
@WilliamAntonRohm FYI - this is a new syntax being shipped for Try .NET
With this, you don't need to modify the samples anymore and we can use whole classes

[Internal Review Example](https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?branch=pr-en-us-3769&view=netframework-4.8)

### CODE REVIEW

**Comment by BillWagner** [comment]
Hmmmm. I tried on the review site [here](https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?branch=pr-en-us-3769&view=netframework-4.8) and the focus mode isn't working. I don't know if that's a resource issue or not.

**Comment by LadyNaggaga** [comment]
@BillWagner  I tried it as well see the issue.

**Comment by wadepickett** [comment]
@mairaw  and @BillWagner  I get the same focus issue.  Selecting "run" results in the UI popping up, but the code does not fill in and you get an endless "busy" green button.

**Comment by mairaw** [comment]
I can't remember if it was doing that before I added the second commit. Let me do a different change on a separate API to test.

**Comment by mairaw** [comment]
So the new example built and it makes no difference.
https://review.docs.microsoft.com/en-us/dotnet/api/system.math.round?view=netframework-4.8&branch=pr-en-us-3769

The first interactive sample uses the old syntax and runs fine. 

The other one uses the new syntax and the issue happens again.

**Comment by mairaw** [comment]
@rloutlaw here are my findings with my latest tests:
- Using just the ID number instead of whole snippet name doesn't work. It just loads the entire file.
   Change: https://github.com/dotnet/dotnet-api-docs/pull/3769/commits/6146276b48738196125c4991d18cddc1d4848c10
   [Review URL](https://review.docs.microsoft.com/en-us/dotnet/api/system.random?branch=pr-en-us-3769&view=netframework-4.8#retrieve-the-same-sequence-of-random-values)
- Same happens if I put a bad snippet ID. Expected: ideally I'd get a warning or a missing snippet (current behavior with the other syntax I believe)
   Change: https://github.com/dotnet/dotnet-api-docs/pull/3769/commits/5f452e2d2ad267ecce4c38d105325cd392be7c8a
   [Review URL](https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.contains?view=netframework-4.8&branch=pr-en-us-3769#examples)
- snippet tag with inner snippet tags - behavior still TBD (build needs to finish)
   [Review URL](https://review.docs.microsoft.com/en-us/dotnet/api/system.object?branch=pr-en-us-3769&view=netframework-4.8#examples)
- Can we use the # syntax like we used to for source paths? Or is that not supported in the new syntax?

**Comment by mairaw** [comment]
Changing the interactive type made the sample load and run.
https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?branch=pr-en-us-3769&view=netframework-4.8#code-try-1

However, we still need to clear the snippets comments from the resulting code.

**Comment by wadepickett** [comment]
Works now, hooray!  I ran it on Chrome and Edge.

**Comment by mairaw** [comment]
You scared for a second @wadepickett 😄 There's no C++ code running, It's just missing so it displays C# code as a fallback.

**Comment by wadepickett** [comment]
@mairaw , yes, sorry, no C++ code running of course!  
The language drop down does stick and show C++ even though the page is C#, which it also does on the live site.  Is that an issue already filed by chance?

**Comment by mairaw** [comment]
I think the behavior you're seeing @wadepickett is by design. When you select C++, if there are no C++ samples available, it will show an example from a fallback language. In this case, C#.
Are you seeing anything different?

**Comment by mairaw** [comment]
Checking if bad ID will be caught by build now

**Comment by mairaw** [comment]
Snippet comments stripping was deployed to production. Testing.

**Comment by mairaw** [comment]
Status update:
- Build warnings are still not reported for bad snippet IDs
- Snippet comments are being stripped but not totally. If you reference the entire file, the most external comments are still rendering

**Comment by mairaw** [comment]
Status update:

- Build warnings are still not reported for bad snippet IDs
- Snippet comments are being stripped but not totally. If you reference the entire file, the most external comments are still rendering but the workaround is to reference that snippet ID surrounding the snippet, unless you want to update the sample.

This should be good to merge once we confirm that my latest change works for the system.object page

**Pull request merged**
