### PR TITLE
Fix parameter comment noCustomTypeDesc

### PR DESCRIPTION
**Pull request by StefanBertels**
## Fix documentation of TypeDescriptor methods / parameter noCustomTypeDesc

Found this documentation bug when reading about `GetConverter` and looking into source code.
I applied same fix to other occurrences (assuming parameter name is correct there, too, and comments wrong).

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=5176) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=5176) before we can accept your contribution.<br/><br/>:x: StefanBertels [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=5176)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-api-docs?pullRequest=5176) it.</sub>

**Review by tarekgh — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by mairaw** [comment]
@StefanBertels can you make sure the CLA is signed? Thanks.

**Comment by gewarren** [comment]
Ping @StefanBertels

**Comment by gewarren** [comment]
Closing in favor of #7195 since the CLA hasn't been signed.

**Pull request closed without merging**
