### PR TITLE
add missing return value

### PR DESCRIPTION
**Pull request by mairaw**
/cc @carlossanlop

### CODE REVIEW

**Comment by carlossanlop** [comment]
Thanks for letting me know. This is one of the namespaces that my tool caught in my latest execution. I'll avoid a conflict if I see it.

**Comment by carlossanlop** [comment]
@safern is the area owner for System.Collections.

**Comment by mairaw** [comment]
I don't think you'll find conflicts for these that I tagged you. They are missing in source as well.
I was just trying to knock a few I saw in the undocumented report that had summary but not return value.

**Comment by mairaw** [comment]
I can't find the nit @rpetrusha!

**Comment by rpetrusha** [comment]
I can't find it either, @mairaw. It has to have been incidental to your PR.

**Pull request merged**
