### PR TITLE
Split <block subset="none" type="note"><para> to different lines

### PR DESCRIPTION
**Pull request by daxianji007**
Split `<block subset="none" type="note"><para>` to different lines

Make content compliant for both dfm and markdig. And prepare for markdown engine switch.

### CODE REVIEW

**Comment by mairaw** [comment]
It seems this change gets undone every time we run CI:
https://github.com/dotnet/dotnet-api-docs/commits/4e4532d3f05c95e9bdc397c505769749ef4e7252/xml/Microsoft.Build.Tasks/ResolveAssemblyReference.xml

We'd need to file a request for @joelmartinez not to undo this when we run CI.

**Comment by joelmartinez** [comment]
@mairaw So this is something that's simply 100% down to the `XmlDocument` APIs, and how they format XML when they save … mdoc isn't doing anything special here, but these changes will always happen because those XML APIs want to format the Xml a certain way.

Our experience with documenting Xamarin APIs (mainly @lobrien and his team) has shown us that we pretty much just have to train authors, and tweak tools that edit the XML outside of mdoc, to avoid these kinds of whitespace changes. In the face of outside contributions, obviously we won't be able to control for that every time, but it's a consideration to make.

**Comment by daxianji007** [comment]
@mairaw @joelmartinez I'm just curious that : 
1. where can we put the node  `<block subset="none" type="note"><para></para></block>` in the xml ? Currently I find it can be sub node of <block>, <value>,<returns>
2. what should this node look like in the page? I go to the page and find it shows as a normal paragraph.

**Comment by lobrien** [comment]
We have only 3 instances of `block type='note'` in our API docs and only 26 uses of `block` in any form (mostly `type=overrides` or `type=behaviors`). If this is causing trouble it would be a reasonably straightforward job to remove them.

**Comment by BillWagner** [comment]
@mairaw Is this one ready to merge?

**Pull request closed without merging**
