### PR TITLE
Update equals_ex4.cs

### PR DESCRIPTION
**Pull request by IvanStoychev**
## Summary

Fixed wrong output shown in commented part of snippet.

Upon running the snippet code an output, different from the one in the documentation, is produced.

### CODE REVIEW

**Comment by IvanStoychev** [comment]
I was not aware of the ICU change, I agree it's probably it.

In my opinion, the best option would be to have different versions of the snippet for the 3.1 and 6 versions, which would be toggled from the version dropdown in the upper-left corner.

Can I help with the overhaul or is this something that needs to be done internally?

**Comment by gewarren** [comment]
For this example, it doesn't add anything above the first example in the Examples section, so I suggest we delete the snippet files and intro text. Would you like to help with that @IvanStoychev ?

**Comment by IvanStoychev** [comment]
Absolutely, @gewarren !

Just committed the changes. Take a look and let me know if it's OK, since I'm not sure how the docs are put together or how to debug / visualise them.

On an unrelated note - should I mention people in comments?
It is my understanding participating in a pull request / thread subscribes a person to it.

**Review by gewarren — APPROVED** [review]
Great, thank you!

**Comment by gewarren** [comment]
> Just committed the changes. Take a look and let me know if it's OK, since I'm not sure how the docs are put together or how to debug / visualise them.

Unfortunately there's no way for external contributors to visualize the changes, but it looks good, and the build will catch any issues if there are other places that reference the deleted snippets.

> On an unrelated note - should I mention people in comments? It is my understanding participating in a pull request / thread subscribes a person to it.

Yes, if you participate then you're automatically notified (usually - it may be configurable).

**Comment by gewarren** [comment]
Looks like we need to remove the F# source file from the F# project.

**Comment by IvanStoychev** [comment]
Yes, was just looking into that.
Would you like me to do it?

**Pull request merged**
