### PR TITLE
Improve link text for MinValue and MaxValue

### PR DESCRIPTION
**Pull request by gewarren**
Sometimes it's helpful to see _typename_._fieldname_ instance of just _fieldname_.

[Preview](https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.tryadd?view=net-7.0&branch=pr-en-us-8104#system-collections-concurrent-blockingcollection-1-tryadd(-0-system-timespan)) (look at exceptions).

### CODE REVIEW

**Comment by gewarren** [comment]
Setting to draft mode until the next version of mdoc releases.

**Comment by gewarren** [comment]
@dotnet/docs Could you review this? It's just cosmetic changes (changes link text).

**Comment by RussKie** [comment]
👍  No objections for Windows Forms.

**Review by tdykstra — APPROVED** [review]
LGTM

**Pull request merged**
