### PR TITLE
metadata updates

### PR DESCRIPTION
**Pull request by mairaw**
Related to https://github.com/dotnet/docs/issues/5062

### CODE REVIEW

**Comment by rpetrusha** [comment]
Sorry, @mairaw. I didn't notice that this was a work in progress. (I seem to be doing well with your PRs today -- one inadvertently merged, one carelessly approved.)

**Comment by mairaw** [comment]
No worries @rpetrusha. I wanted to test my first set of changes but the metadata update on this repo will be a bit trickier because of all the metadata files.

**Comment by mairaw** [comment]
Removing WIP label. I think on a second PR we could move more of the individual writer and manager assignments to a global setting. But I think I cleaned up most of the old membership and hopefully no build issues left.

**Comment by mairaw** [comment]
Forgot to remove the WIP from the label before. @rpetrusha can you take a quick look again?

**Pull request merged**
