### PR TITLE
Mark SocketException versions

### LINKED ISSUE #6658: Remove SokcetException from Begin*** methods for 6.0
There is an ongoing refactor in 6.0 (https://github.com/dotnet/runtime/issues/43845), resulting in the `Socket.Begin***` methods no longer throwing `SocketException`. We should remove `SocketException` from the exception list of the methods being refactored for 6.0, hopefully all of them.

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #6658

### CODE REVIEW

**Comment by gewarren** [comment]
@antonfirsov Can you review? Also, it seems like `BeginConnect (string host, int port, AsyncCallback? requestCallback, object? state)` never threw a SocketException?

**Comment by antonfirsov** [comment]
@gewarren on vacation now, if no one will be faster than me, will review by end of next week.

**Comment by gewarren** [comment]
@antonfirsov Looks like no one else picked this up, so could you review it?

**Review by antonfirsov — APPROVED** [review]
LGTM! Apologies for forgetting about this, hope we can still merge this on time.

**Pull request merged**
