### PR TITLE
fix: Underscore astoria snippets

### PR DESCRIPTION
**Pull request by nschonni**
Related to https://github.com/dotnet/samples/pull/810

### CODE REVIEW

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by rpetrusha** [comment]
There are also four broken code references in this PR, @nschonni. See the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C11%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C201904112122091037-2291%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XuhS%2Bfs%2FuOdIb%2F1wPjJVI1xTOXOJdwPyp%2BhmB2BU%2B3w%3D&st=2019-04-11T22%3A38%3A45Z&se=2019-05-12T22%3A43%3A45Z&sp=r).

**Comment by mairaw** [comment]
Restarting build after I merged the latest PR

**Comment by nschonni** [comment]
@mairaw looks like this one is OK now

**Comment by mairaw** [comment]
Yes!

**Pull request merged**
