### PR TITLE
Port Windows.UI.Xaml source code comments to Docs

### PR DESCRIPTION
**Pull request by carlossanlop**
Automatically ported triple slash source code comments found in Windows.UI.Xaml that were not yet documented in dotnet-api-docs.

Note:
- System.Runtime.WindowsRuntime.UI.Xaml is how the namespace shows up in the code.
- Windows.UI.Xaml is how it shows up in Docs.

### CODE REVIEW

**Comment by carlossanlop** [comment]
@mairaw  @rpetrusha  please take a look.
Maira gave me these comments to automatically port with the tool, so they should be good. But just in case, please help me double check that the formatting was not unexpectedly lost. For example, the tool is unable to save `&lt;see /&gt;` properly. Instead, it literally saves `&amp;lt;see /&amp;gt;`, and I always have to batch-replace those manually. The problems is that xml elements inside xml elements, if they are treated as text, they are saved with less-than and greater-than symbols escaped. I have yet to find a way to prevent this without losing all tabs.

**Comment by mairaw** [comment]
Thank you so much @carlossanlop. I'll make some edits directly if there's any feedback.

**Comment by mairaw** [comment]
@carlossanlop have you noticed that the summaries for the types (T: members) are not being added?

**Comment by carlossanlop** [comment]
@mairaw interesting, No I didn't notice. Thanks for letting me know! I think the tool didn't even know that Types could have summaries. I'll get that fixed and update the PR.

**Comment by mairaw** [comment]
I've already added them manually here but we could be missing them in the other PRs that were previously submitted.

**Comment by carlossanlop** [comment]
@mairaw Wait no, I found the problem, and it's not the fact that Types can have summaries: that didn't matter, the tool was capable of detecting them already. The problem is that the DocId begins with the changed namespace T:Windows.UI... instead of T:System.Runtime.WindowsRuntime..., which is why no match was found. I'm working on a fix.

**Comment by carlossanlop** [comment]
@mairaw thanks for adding them, I appreciate it.

**Pull request merged**
