### PR TITLE
Update MailAddress.xml

### PR DESCRIPTION
**Pull request by rbeinder**
Example text swapped for angle brackets versus quotes.

## Summary

Put the example text along with the correct descriptions.

Fixes dotnet/docs#Issue_Number (if available)

### CODE REVIEW

**Comment by BillWagner** [comment]
ping @davidsh @karelz to check for accuracy.

Once one of you gives the OK, I'll merge this.

**Comment by rbeinder** [comment]
I think my change is not clear somehow. There are two sentences, the first describes angle brackets the second describes quotes. The problme is not the description, it is the following example. The quote example follows the angle bracket description and the angle bracket example follows the quote description.

**Comment by karelz** [comment]
@rbeinder that is not how we understand it (I asked a colleague with English-as-first-language to check my understanding independently).
The example is the input WITHOUT the angle brackets/quotes. It describes the accepted format by the API, not the format it will be turned internally into. Hence my suggestion.

**Comment by BillWagner** [comment]
@rbeinder Are you going to update this per @karelz 's suggestion?

**Comment by rbeinder** [comment]
Updated.

**Comment by mairaw** [comment]
Sorry, we missed your update @rbeinder. There's now a merge conflict. It seems someone else updated this same section.

@karelz do you wanna take a look and see which version do you prefer?

**Comment by BillWagner** [comment]
Closing as the suggested change was made in another PR.

**Pull request closed without merging**
