### PR TITLE
System.Data 1.x undocumented APIs

### LINKED ISSUE #3910: System.Data 1.x undocumented APIs
@ajcvickers @cheenamalhotra @David-Engel @karinazhou @JRahnama @CarlHeinrichs

Here are the undocumented API owned by `System.Data.Common` and `System.Data.SqlClient`. They were all introduced in 1.x. Your team has no debt from 2.x or 3.x (thank you!).
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?
For more information on the plan, see: #3904

Total: 23
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Data.Common.DbCommand.Dispose | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbCommand.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbCommand.Dispose
M:System.Data.Common.DbCommand.Dispose(System.Boolean) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbCommand.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbCommand.Dispose
M:System.Data.Common.DbConnection.Dispose(System.Boolean) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbConnection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnection.Dispose
M:System.Data.Common.DbConnection.Dispose | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbConnection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnection.Dispose
P:System.Data.Common.DbConnectionStringBuilder.System#Collections#IDictionary#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbConnectionStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnectionStringBuilder.System-Collections-IDictionary-IsFixedSize
P:System.Data.Common.DbConnectionStringBuilder.System#Collections#IDictionary#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbConnectionStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnectionStringBuilder.System-Collections-IDictionary-IsReadOnly
P:System.Data.Common.DbParameter.System#Data#IDataParameter#SourceVersion | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbParameter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbParameter.System-Data-IDataParameter-SourceVersion
P:System.Data.Common.DbParameterCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbParameterCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbParameterCollection.System-Collections-ICollection-IsSynchronized
P:System.Data.Common.DbParameterCollection.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbParameterCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbParameterCollection.System-Collections-IList-IsFixedSize
P:System.Data.Common.DbParameterCollection.System#Collections#IList#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbParameterCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbParameterCollection.System-Collections-IList-IsReadOnly
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.Count
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.GetEnumerator
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-ICollection-CopyTo
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-ICollection-IsSynchronized
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-ICollection-SyncRoot
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Add(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Add
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Contains(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Contains
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#IndexOf(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-IndexOf
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Insert(System.Int32,System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Insert
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-IsFixedSize
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-IsReadOnly
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Item
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Remove(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Remove

### PR DESCRIPTION
**Pull request by David-Engel**
## Summary

Takes care of some undocumented APIs owned by System.Data.Common and System.Data.SqlClient. that were all introduced in 1.x.

Fixes #3910

### CODE REVIEW

**Comment by David-Engel** [comment]
Not sure why the CI is not providing a review links, but here are a couple starters:
https://review.docs.microsoft.com/en-us/dotnet/api/system.data.common.dbcommand.dispose?view=netcore-1.1&branch=pr-en-us-4233
https://review.docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopycolumnmappingcollection.count?view=netcore-1.1&branch=pr-en-us-4233

**Comment by carlossanlop** [comment]
Thank you @David-Engel for the PR. The changes look good.
Do any of these APIs throw exceptions? If yes, can you please add them? The xml items for exceptions have to be manually added below the remarks item, like this:

```xml
    <remarks>To be added.</remarks>
    <exception cref="T:System.WhateverException">The reason why the exception is thrown.</exception>
```

**Comment by David-Engel** [comment]
@carlossanlop 

> Do any of these APIs throw exceptions? If yes, can you please add them?

Added.

**Comment by ajcvickers** [comment]
Thanks @David-Engel!

**Comment by David-Engel** [comment]
@carlossanlop Anything else needed before merging this PR?

Thanks,
David

**Pull request merged**
