### PR TITLE
Add documentation for ConsoleKey.None and ConsoleModifiers.None

### PR DESCRIPTION
**Pull request by terrajobst**
## Summary

This adds reference documentation for https://github.com/dotnet/runtime/pull/83114.

/cc @stephentoub @carlossanlop

### CODE REVIEW

**Comment by gewarren** [comment]
I think there was a misunderstanding - Stephen was referring to XML comments in the ///, not here. I think we should close this PR since we don't want to publish it before Preview 3.

**Comment by terrajobst** [comment]
@gewarren 

> I think there was a misunderstanding - Stephen was referring to XML comments in the ///, not here. I think we should close this PR since we don't want to publish it before Preview 3.

For some assemblies we currently don't do ///, which includes these two types. How are those being documented then? Or is this just a function of waiting until automation populates the API entry in this repo?

**Comment by gewarren** [comment]
Yes, wait until automation populates the XML files in this docs repo. Even if you're not building documentation files when you compile, Carlos can use his tool to port the comments over from ///. However, he said that he's not going to do that until RC, so if you wanted to add descriptions before RC, you can come back here when Preview 3 ships and update the `<summary>` manually.

**Comment by terrajobst** [comment]
Sounds good, will do. Thanks!

**Pull request closed without merging**
