### PR TITLE
Add .net interactive

### PR DESCRIPTION
**Pull request by mairaw**
This is a repro for bug https://dev.azure.com/ceapex/Engineering/_workitems/edit/212902
and https://ceapex.visualstudio.com/Engineering/_workitems/edit/214972

Edit: bugs have been fixed. This adds interactive to one of the samples that was problematic

### CODE REVIEW

**Comment by jeffhandley** [comment]
@mairaw I wasn't sure what the next step for this PR was. Is there something to finish here, or can this be closed? Thanks!

**Comment by mairaw** [comment]
It's marked as draft so I can validate the bug fixes when they're in. I'll check their status.

**Comment by jeffhandley** [comment]
Thanks, @mairaw. Sorry I overlooked the Draft status; my bad.

**Comment by mairaw** [comment]
Only https://ceapex.visualstudio.com/Engineering/_workitems/edit/212902 left to be tested. Reset the repo and added just the change to be tested.

**Comment by mairaw** [comment]
Test URL: https://review.docs.microsoft.com/en-us/dotnet/api/system.string.trimstart?view=net-5.0&branch=pr-en-us-4175

**Comment by mairaw** [comment]
@BillWagner @gewarren can you review this? should be quick

**Review by gewarren — APPROVED** [review]

**Pull request merged**
