### PR TITLE
remove incorrect exception condition

### PR DESCRIPTION
**Pull request by mairaw**
Fixes [internal doc bug](https://devdiv.visualstudio.com/DevDiv/_queries?id=130543&triage=true&fullScreen=false&_a=edit)

### CODE REVIEW

**Comment by mairaw** [comment]
@kouvel did I capture your feedback correctly from [the bug](https://devdiv.visualstudio.com/DevDiv/_queries?id=130543&triage=true&fullScreen=false&_a=edit)?

**Comment by kouvel** [comment]
I think I misread the first condition for the exception. It is correct, though with some adjustments (rephrased as condition for exception similar to the other statements, and qualified), maybe something like this:

"The current thread has attempted to acquire a write lock when it already holds a read lock and does not already hold another write lock."

**Comment by mairaw** [comment]
@kouvel I'm slightly confused now. Wouldn't that be the case for the [EnterWriteLock](https://docs.microsoft.com/en-us/dotnet/api/system.threading.readerwriterlockslim.enterwritelock) instead? The [EnterReadLock](https://docs.microsoft.com/en-us/dotnet/api/system.threading.readerwriterlockslim.enterreadlock) doesn't attempt to acquire a write lock, correct?

**Comment by kouvel** [comment]
Ah, I lost that context. I agree, removing that first statement (your current change) looks right to me. Thanks!

**Comment by kouvel** [comment]
But also in the docs for EnterWriteLock that I see here anyway: https://msdn.microsoft.com/en-us/library/system.threading.readerwriterlockslim.exitwritelock(v=vs.110).aspx

There is very limited documentation on exception cases. I guess I'm using old doc links, what is the current set of docs that I should be querying?

**Comment by kouvel** [comment]
Oh you already linked it, I'll check it

**Comment by mairaw** [comment]
The APIs are all moving to https://docs.microsoft.com/en-us/dotnet/api/. We hope to set up the redirection soon. We're making all the improvements on docs only but a lot of the content still looks the same as msdn like the https://docs.microsoft.com/en-us/dotnet/api/system.threading.readerwriterlockslim.exitwritelock example.

**Comment by kouvel** [comment]
From https://docs.microsoft.com/en-us/dotnet, I see several links to netfx docs, netcore docs, netstandard docs, etc. Would this change apply to all of them (it's applicable to all of them)?

For the docs for EnterWriteLock that you linked above, for this statement:

> "The current thread has entered read mode, so trying to enter the lock in write mode would create the possibility of a deadlock."

It could be qualified that that situation described is only an issue when a write lock is not already held by the thread. That is, {EnterReadLock, EnterWriteLock} is bad if the thread doesn't already own a write lock and will throw an exception due to deadlock possibility, but {EnterWriteLock, EnterReadLock, EnterWriteLock} is ok when the lock recursion policy allows recursive lock acquisition.

**Comment by mairaw** [comment]
Yes, the source is one for all of the them, but choosing one of the targets will give you a different list of APIs. If there are different behaviors for Core, etc., we call out in the text.

**Comment by kouvel** [comment]
I see, thanks. I'm aware of one doc that lists differences between the runtimes, this issue covers it: https://github.com/dotnet/docs/issues/3640

I believe it was created for the 2.0 release but I'm not sure if it has been updated. For instance when I'm looking at netfx docs it would be nice to see that the API is not supported or has different behavior in netcore, or vice versa.

**Comment by mairaw** [comment]
Yes, I'd love to get to that issue soon. Our team has been swamped and couldn't get started on this yet unfortunately. 😢

**Comment by mairaw** [comment]
@kouvel can you make sure that the change I made for EnterWriteLock is correct?

**Comment by kouvel** [comment]
LGTM, thanks!

**Pull request merged**
