### PR TITLE
missing docs for System.Runtime.InteropServices.JavaScript

### PR DESCRIPTION
**Pull request by pavelsavara**
- add missing summary for the namespace
- generate missing doc from the runtime repo

Together with https://github.com/dotnet/runtime/pull/76196

### CODE REVIEW

**Review by gewarren — APPROVED** [review]

**Comment by gewarren** [comment]
Oh sorry, I thought you were just re-requesting review from docs. Is it okay that I merged it?

**Comment by pavelsavara** [comment]
Yes :) 
I will try to use the tool to put your grammar changes back to runtime repo on that open PR.

**Comment by carlossanlop** [comment]
> Yes :) I will try to use the tool to put your grammar changes back to runtime repo on that open PR.

Unfortunately that won't work, @pavelsavara. The docs porting tool only ports _new_ documentation (when the dotnet-api-docs xml elements have the `To be added.` boilerplate message).

If you want to bring your triple slash comments to dotnet-api-docs, you'll have to manually edit the files.

**Comment by gewarren** [comment]
I think Pavel is going in the opposite direction (dotnet-api-docs -> runtime repo).

**Comment by carlossanlop** [comment]
Ah, good!

**Pull request merged**
