### PR TITLE
Added VB sample link

### PR DESCRIPTION
**Pull request by arjanvanhuizen**
These changes contributes to:
#990

The referenced examples are related to PR:
dotnet/samples#735
https://github.com/dotnet/samples/pull/739

### CODE REVIEW

**Comment by mairaw** [comment]
Closing and reopening now that https://github.com/dotnet/samples/pull/735 was merged.

**Comment by mairaw** [comment]
There were still a couple of warnings that I believe were fixed with https://github.com/dotnet/samples/pull/739

**Comment by arjanvanhuizen** [comment]
@rpetrusha @mairaw Do you know why the new VB link on line 228 disappeared in the xml file?
@rpetrusha I will modify the xml file further and put the link on every line you've provided in your previous post, Thank you,

**Comment by rpetrusha** [comment]
The VB link on line 228 is still there, @arjanvanhuizen.

**Comment by mairaw** [comment]
@arjanvanhuizen let us know if you need any help finishing this PR

**Pull request merged**
