### PR TITLE
.NET 5 RTM APIs

### PR DESCRIPTION
**Pull request by gewarren**
(From CI job.)

This is deleting a bunch of MSBuild APIs. @ghogen I'm guessing this is not okay? Maybe I can just exclude all the Microsoft.Build.* files from this PR, but it would be good to know why they're being deleted.

### CODE REVIEW

**Comment by gewarren** [comment]
I ended up reverting all the MSBuild changes. I'm guessing that is what we want here.

**Comment by BillWagner** [comment]
Hmm. I'm a bit confused. I'm see a large number of missing moniker warnings for releases that should be present (.NET Core 3.1, .NET Core 2.1, .NET 5). Any ideas why?

**Comment by gewarren** [comment]
> Hmm. I'm a bit confused. I'm see a large number of missing moniker warnings for releases that should be present (.NET Core 3.1, .NET Core 2.1, .NET 5). Any ideas why?

Warnings like that have been present in the repo for a couple months, at least. I just asked about it on the FC .NET Infrastructure channel though.

**Comment by gewarren** [comment]
I've updated the monikers for .NET 5 and .NET Platform Extensions 5. Can someone approve this PR so we can publish it?

**Review by BillWagner — APPROVED** [review]
I reviewed several pages on the review site, and browsed some of the changes. After @gewarren answered my question regarding warnings, this is ready to :shipit:

**Comment by gewarren** [comment]
Thanks Bill!

**Pull request merged**
