### PR TITLE
DO-NOT-MERGE -- testing Ecma2Yaml and mdoc pre-release

### PR DESCRIPTION
**Pull request by joelmartinez**
Testing some upcoming plugin and template changes in this branch

### CODE REVIEW

**Comment by mairaw** [comment]
Better to use draft PRs now. WIP bot was removed from the org.

**Comment by joelmartinez** [comment]
@mairaw will a draft PR still kick off an OPS build? I was under the impression that it wouldn't ... but I'd be happy to close this and re-open just a draft PR if that's the case :)

**Comment by mairaw** [comment]
yes @joelmartinez. Draft PRs still kick off a build. Do you still need this one?

**Comment by joelmartinez** [comment]
oh, no ... thanks for following up @mairaw  :)

**Pull request closed without merging**
