### PR TITLE
typos: xml/System.[E-L]*

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
Think it might not like the branch name, I might need to resubmit it

**Comment by mairaw** [comment]
Really weird @nschonni. I'll follow up with our engineering team as well.

**Comment by nschonni** [comment]
>      * [new branch]            typo-hander -> 1445dff73881564953d443a7c5e1120e/typo-hander
    error: cannot lock ref 'refs/remotes/1445dff73881564953d443a7c5e1120e/typos--cspell-"xml/System.D-/--/-.-"': unable to create directory for .git/refs/remotes/1445dff73881564953d443a7c5e1120e/typos--cspell-"xml/System.D-/--/-.-"
     ! [new branch]            typos--cspell-"xml/System.D-/--/-.-" -> 1445dff73881564953d443a7c5e1120e/typos--cspell-"xml/System.D-/--/-.-"  (unable to update local ref)
     * [new branch]            typos-System.E- -> 1445dff73881564953d443a7c5e1120e/typos-System.E-
   
It's actually the other PR's branch that it's choking on. I'll close that one and see if it gets happier

**Comment by nschonni** [comment]
Deleting the other branch seems to have cleared it

**Pull request merged**
