### PR TITLE
updating Hashset`1.xml for Try .NET

### PR DESCRIPTION
**Pull request by WilliamAntonRohm**
samples PR is https://github.com/dotnet/samples/pull/1533

### CODE REVIEW

**Comment by WilliamAntonRohm** [comment]
@mairaw, @BillWagner -- please review these updates at your convenience.

**Comment by Thraka** [comment]
Just FYI I tried the [first snippet on the hashset article](https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.8&branch=pr-en-us-3222#code-try-1) and it wouldn't compile and run in the try browser

**Comment by WilliamAntonRohm** [comment]
@Thraka -- Andy, that *is* strange.  The updated sample files have been merged, so this snippet should be working.

@mairaw, @BillWagner -- in that generated article's HTML page source, I see my own fork referenced (?!) for the data-src -- how can I fix that?
```
<pre><code class="lang-csharp" data-interactive="csharp" data-src="https://github.com/WilliamAntonRohm/dotnet-api-docs/blob/hashset/snippets/csharp/VS_Snippets_CLR_System/system.Collections.Generic.HashSet_UnionWith/cs/Program.cs" name="System.Collections.Generic.HashSet_UnionWith#01">using System;
```

**Comment by mairaw** [comment]
After the samples are merged, two things need to happen:
- An internal build of the target branch needs to be done (but since it has been so long the master branch has been built many times)
- This PR needs to be rebuilt

**Comment by WilliamAntonRohm** [comment]
Replaced by new PR https://github.com/dotnet/dotnet-api-docs/pull/3430.

**Pull request closed without merging**
