### PR TITLE
Add snippets 5000 check

### PR DESCRIPTION
**Pull request by adegeo**
## Summary

- Enables the Snippets 5000 build check

### CODE REVIEW

**Review by gewarren — APPROVED** [review]
Thanks for adding this!

**Comment by gewarren** [comment]
@danmoseley FYI we're adding a status check to this repo that builds any code snippets that are modified. But if the code snippet isn't associated with a project file, then you'll see a (non-blocking) error that asks you to add a project file.

**Comment by danmoseley** [comment]
@gewarren nice. I'm forgetting any context here. has the engineering team typically provided snippets (at least in recent times)? do we know how to offer new ones?

**Comment by gewarren** [comment]
@danmoseley I don't think there have been many code snippets (which are short examples that live in the dotnet/dotnet-api-docs repo) or samples (which are more complex examples that live in the dotnet/samples repo) contributed by the engineering team in recent times. But I am fairly new to the team. @BillWagner could maybe provide more insight into that.

The overall guidelines are [here](https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-contribute).

This was more just an FYI that there will be a new status check if someone changes any code snippets, and they will likely have to add a new project file to the repo.

**Comment by danmoseley** [comment]
just curious, why is a project file helpful?

if it's important, maybe if I add an entirely new snippet, it could block if it isn't in a project (new or existing)?

**Comment by gewarren** [comment]
Snippets 5000 uses the project file to build the snippet. And yes, it will fail if you add a new snippet that's not part of a project.

**Pull request merged**
