### PR TITLE
System.Convert F# snippets

### PR DESCRIPTION
**Pull request by albert-du**
Adds F# snippets for Convert

### CODE REVIEW

**Comment by albert-du** [comment]
@dsyme Could you review?

**Review by BillWagner — COMMENTED** [review]
I have this a good look, and everything looks good to me.

There's a lot here, so I'd appreciate @dsyme looking before we merge this.

(Commenting rather than approving so this stays in my review queue)

**Comment by albert-du** [comment]
@BillWagner this is ready

**Comment by albert-du** [comment]
@BillWagner this is ready to be merged

**Review by dsyme — APPROVED** [review]

**Review by BillWagner — APPROVED** [review]
This LGTM.

**Comment by BillWagner** [comment]
@albert-du  I apologize for the delay. This slid out of my review queue. I'll figure out why the GitHub notifications are behaving a bit differently than I thought.

**Pull request merged**
