### PR TITLE
Clarify Interlocked.{In|De}crement

### PR DESCRIPTION
**Pull request by Smaug123**
## Summary

Fix some ambiguous English. Was "the decremented value" the value that was decremented, or the value after it was decremented? A bit of thought indicates that it must be the latter (otherwise the API is useless), but why make the user do that thinking.

### CODE REVIEW

**Review by kouvel — APPROVED** [review]
Thanks!

**Comment by kouvel** [comment]
Actually it would probably be good to update all of the other overloads in the same change. @Smaug123 if you want to do that, that would be great, or I can do so later.

**Comment by Smaug123** [comment]
Ah sorry, I didn't think to search for other overloads 🤦 coming up.

**Comment by kouvel** [comment]
Much appreciated, thanks!

**Pull request merged**
