### PR TITLE
Match labels to trackbars according to RGB order

### PR DESCRIPTION
**Pull request by TarenLewis**
## Summary

Matched Label2 with Green value, and Label3 with Blue value in accordance with RGB order (1,2,3), and also to match the trackbar numbers (1,2,3). Improves readability and lowers risk of confusion.

### CODE REVIEW

**Comment by gewarren** [comment]
@TarenLewis I don't actually see that the code you modified is used in the documentation anywhere, only snippet4 (lines 64-93). Were you just browsing the code when you noticed this?

**Comment by TarenLewis** [comment]
@gewarren Yes, I noticed this "issue" in the documentation located here:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.trackbar.scroll?view=netcore-3.1
It seems counterintuitive to me that the naming conventions would be:

label1 --> trackbar1
label3 --> trackbar2
label2 --> trackbar3 

Thats why I swapped the coordinates, and renamed the labels accordingly to fit RGB order and "better" naming conventions. The code seemed confusing to me when I first looked at it, that's why I did this.

**Comment by gewarren** [comment]
I see it now, thanks. One problem is that the C++ and VB snippets still have the previous order of the labels. Could you update those too?

**Comment by TarenLewis** [comment]
Yes, I will take care of those fixes as well.

**Comment by gewarren** [comment]
@TarenLewis Are you still working on the VB/C++ snippets? Could you add them to this PR?

**Comment by gewarren** [comment]
Closing in favor of #9997.

**Pull request closed without merging**
