### PR TITLE
Updating Microsoft.Build

### PR DESCRIPTION
**Pull request by v-alje**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by gewarren** [comment]
I don't see that a FrameworksIndex file has changed - which I think means there are no new/removed APIs and no other API changes. Just doc comment changes. Is that expected?

**Comment by v-alje** [comment]
@gewarren You are correct. I am missing that. I'll add the missing files.

**Comment by gewarren** [comment]
But there shouldn't be any changes to files other than MSBuild right? This makes me a bit nervous if there are other changes not being included in the PR, because that would mean some sort of "dirty" state.

**Comment by v-alje** [comment]
The smoke-test-msbuild branch was deleted before running the CI job, which recreated the branch from main and updated that.  
 
There are thousands of changes from the CI job run. All of the changes I have looked at so far in random sampling, outside of the msbuild changes, are moving the C++ TypeSignature Language tag to the top of the list.   

The [Diff](https://github.com/dotnet/dotnet-api-docs/compare/smoke-test-msbuild..main) is too large to view on GitHub so, I am looking at them as a local dif on my machine.

**Comment by gewarren** [comment]
I think I know what happened. When they updated mdoc to 5.8.3, I didn't run the CI job, so this includes all of those mdoc changes. I have a job running now that will be finished in a couple of hours. Can you wait for me to merge that before you merge this one? That way you should be able to see the msbuild changes more easily.

**Comment by v-alje** [comment]
@gewarren Sounds good!

**Comment by gewarren** [comment]
Shoot, sorry Alma. It looks like you may need to rerun the CI job?

**Comment by v-alje** [comment]
@gewarren Okay, I will do that.

**Comment by v-alje** [comment]
@gewarren I'm still getting thousands of updates in the smoke-test-msbuild branch to change the ordering of the TypeSignature Language elements to place C++ at the top of the list.

**Comment by gewarren** [comment]
> @gewarren I'm still getting thousands of updates in the smoke-test-msbuild branch to change the ordering of the TypeSignature Language elements to place C++ at the top of the list.

I saw that. It probably has something to do with differences in the CI job configuration:

image

I have that box checked for regular API updates.

**Comment by v-alje** [comment]
@gewarren Thanks! I will give that a try, and regenerate the smoke-test-msbuild branch.

**Comment by v-alje** [comment]
@ghogen Here are the MSBuild changes.

**Review by gewarren — APPROVED** [review]

**Review by ghogen — APPROVED** [review]

**Review by ghogen — APPROVED** [review]

**Pull request merged**
