### PR TITLE
Fix bad links - various namespces

### PR DESCRIPTION
**Pull request by gewarren**
Contributes to #10311.

([Hide whitespace changes](https://github.com/dotnet/dotnet-api-docs/pull/10313/files?diff=unified&w=1).)

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
`System.Runtime.InteropServices` LGTM.

**Review by rzikm — APPROVED** [review]
System.Net.* LGTM

**Review by BillWagner — APPROVED** [review]
Build looks good to me. Let's :shipit:

**Review by mconnew — APPROVED** [review]
WCF changes look good to me

**Pull request merged**
