### PR TITLE
Fix typo in System.Linq > Enumerable

### PR DESCRIPTION
**Pull request by ilserd**
## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by gewarren** [comment]
@ilserd What are the whitespace changes in this file?

**Comment by ilserd** [comment]
> @ilserd What are the whitespace changes in this file?

Sorry, an unintended effect of editing through Github. I should've fixed it now.

**Comment by ilserd** [comment]
@dotnet-policy-service agree company="Geckosoft"

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by gewarren** [comment]
Thank you @ilserd

**Pull request merged**
