### PR TITLE
Added link in AesManaged to article warning of timing vulnerabilities…

### PR DESCRIPTION
**Pull request by samrueby**
… with CBC-mode symmetric decryption using padding.

## Summary

Added a link to an important article from Microsoft about the latest recommendations for securely handling encrypted data while using CBC mode, which is the default for this class.

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks for your contribution @samrueby. @bartonjs can you please take a look? I can make the suggestions from a content perspective after the tech review is done.

**Comment by bartonjs** [comment]
Seems fine to me.

**Comment by mairaw** [comment]
It would probably be good to add this info to the Mode property remarks as well.

**Comment by samrueby** [comment]
Possibly- but according to the article a lot of other types are apparently affected too: 

Aes
AesCng
AesCryptoServiceProvider
AesManaged
DES
DESCryptoServiceProvider
RC2
RC2CryptoServiceProvider
Rijndael
RijndaelManaged
TripleDES
TripleDESCng
TripleDESCryptoServiceProvider

Should all of them be updated?

**Comment by mairaw** [comment]
@bartonjs can you comment on that?

**Comment by bartonjs** [comment]
Yes, all of those named types are similarly affected (by having CBC+PKCS7 be the default and CBC with any removable padding being what has the vulnerabilty).

**Comment by tdykstra** [comment]
@samrueby Do you want to update all of the other types you listed, or should we merge this PR and create an issue to track the work of updating the others?

**Comment by BillWagner** [comment]
@tdykstra 

At this point, I think we should merge this, and create a new issue for the remaining changes. Do you agree?

**Pull request merged**
