### PR TITLE
CI Update - .NET 8 Preview 6

### LINKED ISSUE #9042: Update API docs for Preview 6

### PR DESCRIPTION
**Pull request by gewarren**
Build.Reason:Manual by Genevieve Warren
 Build.Url:https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=373330&view=results
 source_repo.branch:net8-pre6
 source_repo.url:https://apidrop.visualstudio.com/_git/binaries

.NET 8 Preview 6

Fixes #9042.

### CODE REVIEW

**Review by carlossanlop — APPROVED** [review]
Assuming the expected WCF files are found here, and the recent extension updates are reflected, LGTM. I tried to navigate through some files but GitHub crashes after a few minutes of trying to load them.

**Comment by ProIntegritate** [comment]
Not sure if this comment is in the right place, but i don't know how to message someone on github or comment the page as there is no "provide feedback" option on it. I'm guessing it belongs here:

-

Just a note on this page:
https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm?view=net-8.0

The function AesGcm now requiring a Byte array with Keybytes AND a Tag size in bytes - this is not applicable for .NET 6 and earlier as they only need a Byte array with Keybytes to be created.

The Tag + Nounce can be provided as parameters to the .Encrypt() and .Decrypt() methods. The requirement to add an Int32 with the size of the nounce is something new that i observed in .NET 8 (*) - so the documentation needs an update.  (* i haven't tested it in .NET 7 because it's not LTS and i don't care about non-LTS releases)

I really wonder why this change was necessary at all as it breaks some cryptographic code. The size of the Nounce is always automatically provided by passing a byte array to the methods.

**Comment by gewarren** [comment]
@ProIntegritate Thanks for the note. You can read about why the tag-less constructors were obsoleted in this issue: https://github.com/dotnet/docs/issues/35338. I also created a [PR](https://github.com/dotnet/docs/pull/36265) to add that info to the SYSLIB0053 article.

**Comment by carlossanlop** [comment]
Thanks for reporting this, @ProIntegritate .

 opened an issue in the dotnet/runtime repo on your behalf so the System.Security area owners can take a look at this. https://github.com/dotnet/runtime/issues/88933

If you wish to add some more info, or continue the conversation, please do so in that issue.

**Pull request merged**
