### PR TITLE
Add information about NullReferenceException in ConfigurationRoot ctor

### PR DESCRIPTION
**Pull request by moojek**
## Summary

As in title. Source: https://github.com/dotnet/runtime/blob/049da221a7f0e38eb92ef72fe0611b9b72e513da/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationRoot.cs

### CODE REVIEW

**Comment by moojek** [comment]
Sorry for close and reopen, I must've misclicked something.

**Comment by gewarren** [comment]
Tagging @dotnet/area-extensions-configuration

**Review by tarekgh — APPROVED** [review]
LGTM. 

It is showing some diff in line 239 which unclear to me what exactly change there. Will be good to revert this change.

**Comment by moojek** [comment]
Hi, sorry for the hassle. Maybe it was some autocrlf from git, I don't know - certainly not my personal change. I already reverted it.

**Comment by moojek** [comment]
That's what doing it at 1 am in bed does, huh? I'll correct it later today

**Comment by moojek** [comment]
It was ridiculously hard to correct, but I think all good now @tarekgh :)

**Comment by tarekgh** [comment]
Thanks @moojek!

**Pull request merged**
