### PR TITLE
Update with latest mdoc changes + .NET Core 2.1 Preview 1

### PR DESCRIPTION
**Pull request by dend**

### CODE REVIEW

**Comment by wstaelens** [comment]
@mairaw https://docs.microsoft.com/nl-be/dotnet/api/system.text.regularexpressions.groupcollection?view=netframework-4.7.1 

In the examples section: you have "The example displays the following output:"
but this is not complete as it doesn't show all console.writeline information etc...  

the example should show the exact output that the code has.

**Comment by mairaw** [comment]
@wstaelens I only noticed your message now. Are you still having issues with that page?

**Comment by wstaelens** [comment]
well if you execute that code the console.writeline doesn't 100% match the comments // in the code describing the output ;-)

**Comment by mairaw** [comment]
I misunderstood your earlier comment then. Can you open an issue at https://github.com/dotnet/docs with this information for us to track this? Thanks in advance!

**Pull request merged**
