### PR TITLE
Renamed variable name

### PR DESCRIPTION
**Pull request by LuanRoger**
```record``` is a keyword and must be not a variable name.

### CODE REVIEW

**Comment by vcsjones** [comment]
> `record` is a keyword and must be not a variable name.

As far as I understand it, it's a contextual keyword in C#. `record` should be fine for parameter and variable names. This [compiles and runs](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUH1AZgAINiBRKYMATwAUB7ASyrwG89ivTMA2UgCzEAsgEMWACgCUnbh1zdFPAAzEwAUwDGDMHGIBeYgCJg6gM7AjAbllLidMC2ASN23SDVadcKTYXcAX1tiYNQ+QXtHKgkw1VdvGX8ueTsuMIBOFy9dX2Cg3HygA) just fine:

```c#
using System;

public class EntryPoint
{
    static void Main()
    {
        string record = "test";
        Print(record: record);
    }
    
    static void Print(string record)
    {
        Console.WriteLine(record);
    }
}
```

**Comment by LuanRoger** [comment]
Yes, it works, but I renamed it because in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldatareader?view=dotnet-plat-ext-5.0) it is highlighted as keyword.

**Comment by BillWagner** [comment]
@LuanRoger The OPS build (for the documentation pages) finished, and I checked the review site. The variable name isn't mentioned there, so there's no need for an additional change.

However, this sample was old enough that it never had a project to build for our new CI system. That's the failure reported from the Snippets 5000. The fix should be to add a default *csproj* file in the folder. You may need to specify some packages to resolve the types used.

Let me know what you want to do

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=7281) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=7281) before we can accept your contribution.<br/><br/>:x: LuanRoger [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=7281)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-api-docs?pullRequest=7281) it.</sub>

**Comment by BillWagner** [comment]
> From what I've seen, there are still many files without the default csproj in other folders.

That's correct. We've been adding them as we make any other changes. Admittedly not perfect, but it has helped us balance improving this situation with other work.

**Pull request merged**
