### PR TITLE
Move System.IO.Compression.ZipFile* lengthy remarks to files

### PR DESCRIPTION
**Pull request by carlossanlop**
Based on @gewarren suggestion [here](https://github.com/dotnet/runtime/pull/46716#issuecomment-761061215), I am moving all the lengthy remarks from ZipFile.xml and ZipFileExtensions.xml to their own md files.

This PR is blocking https://github.com/dotnet/runtime/pull/48633

### CODE REVIEW

**Review by gewarren — APPROVED** [review]
LGTM

**Comment by carlossanlop** [comment]
OpenPublishing.Build is stuck and I want to see the preview. Closing and reopening to retrigger the CI.

**Comment by gewarren** [comment]
> OpenPublishing.Build is stuck and I want to see the preview. Closing and reopening to retrigger the CI.

OPS is down and will be for a few more days, unfortunately :(

**Comment by carlossanlop** [comment]
Sorry for the spam, everyone. I pushed the wrong thing and a bunch of unrelated files got added to the PR which triggered the bot to add the owners.

**Pull request merged**
