### PR TITLE
Port System.Collections triple slash to docs

### PR DESCRIPTION
**Pull request by carlossanlop**
Ported with DocsPortingTool.

Targeting net6-rc1 branch.

### CODE REVIEW

**Comment by gewarren** [comment]
Docs Build status updates of commit _[8e12518](https://github.com/carlossanlop/dotnet-api-docs/commits/8e125183a2676f3b0190a9f05904a07c5c86df94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/System.Collections.Generic/List`1.xml](https://github.com/carlossanlop/dotnet-api-docs/blob/upd.collections/xml/System.Collections.Generic/List%601.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=dotnet-uwp-10.0&branch=pr-en-us-7101) |
[xml/System.Collections.Generic/Queue`1.xml](https://github.com/carlossanlop/dotnet-api-docs/blob/upd.collections/xml/System.Collections.Generic/Queue%601.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.generic.queue-1?view=dotnet-uwp-10.0&branch=pr-en-us-7101) |
[xml/System.Collections.Generic/Stack`1.xml](https://github.com/carlossanlop/dotnet-api-docs/blob/upd.collections/xml/System.Collections.Generic/Stack%601.xml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/api/system.collections.generic.stack-1?view=dotnet-uwp-10.0&branch=pr-en-us-7101) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C202109030853463433-7101%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=b6HlyKhsSZOTZscPh0sevq4gFPmrWItI%2BUUgu%2BVRRig%3D&st=2021-09-03T09%3A21%3A14Z&se=2021-10-04T09%3A26%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/500c749d-de78-3d4a-00e4-269d599bf9ec?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by gewarren** [comment]
I don't think this PR is needed. These comments were recently added to main.

https://github.com/dotnet/dotnet-api-docs/pull/7071

**Comment by eiriktsarpalis** [comment]
Was not aware of the `net6-rc1` branch until today. @gewarren @carlossanlop which one should we be targeting for missing docs?

**Comment by gewarren** [comment]
@carlossanlop For this one, I think we should pull main into this branch instead. Because these APIs are already updated in main.

**Comment by carlossanlop** [comment]
Ah okay, thanks for checking, @gewarren. I'll close this.

**Comment by gewarren** [comment]
I've updated net6-rc1 with the latest main.

**Pull request closed without merging**
