### PR TITLE
CI update for mdoc 5.7.6

### PR DESCRIPTION
**Pull request by gewarren**

### CODE REVIEW

**Comment by gewarren** [comment]
@TianqiZhang Are these warnings expected?

api/Microsoft.JScript.Vsa.VsaEngine.Clone.yml

•	[Warning] Unable to find uid "<xref href="Microsoft.Vsa.IVsaEngine?alt=Microsoft.Vsa.IVsaEngine&text=IVsaEngine" data-throw-if-not-resolved="True"/>".
•	[Warning] Unable to find uid "<xref href="Microsoft.JScript.Vsa.IJSVsaEngine?alt=Microsoft.JScript.Vsa.IJSVsaEngine&text=IJSVsaEngine" data-throw-if-not-resolved="True"/>".

api/Microsoft.Build.Utilities.ToolTask.EnvironmentOverride.yml

•	[Warning] Unable to find uid "<xref href="System.Collections.Generic.Dictionary`2?alt=System.Collections.Generic.Dictionary&text=Dictionary" data-throw-if-not-resolved="True"/>&lt;<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>,<xref href="System.String?alt=System.String&text=String" data-throw-if-not-resolved="True"/>&gt;".
•	[Warning] Unable to find uid "<xref href="System.Collections.Specialized.StringDictionary?alt=System.Collections.Specialized.StringDictionary&text=StringDictionary" data-throw-if-not-resolved="True"/>".

**Comment by BillWagner** [comment]
This looks like it has more changes that I would expect, and the merge conflicts are troubling.

Ping @ghogen @v-alje because this may be due to the ongoing work for ms-build releases.  Have those been merged, or are they still pending (and on the master branch)?

**Comment by ghogen** [comment]
@BillWagner @v-alje Alma had used the smoke-test branch for MSBuild testing, so that's likely what this is.  Alma would know more.  Our current work is in the release-msbuild branch.

**Comment by gewarren** [comment]
**smoke-test** branch didn't exist before I ran the job, but I know there is some weirdness with reusing old branch names.

**Comment by v-alje** [comment]
This doesn't look like it has anything to do with the MSBuild changes. We are using the smoke-test-xml and release-msbuild branches, smoke-test was deleted after it was last used, and this is in a different set of libraries from what we are working with.

**Comment by BillWagner** [comment]
@gewarren 

Now that all the work related to MS Build updates has been merged, I think the correct update now is to close this branch, and run the CI again to pickup the latest mdoc engine changes.

Alternatively, you can configure the build to create a new target branch so we can try both.

**Comment by gewarren** [comment]
Closing in favor of #4423.

**Pull request closed without merging**
