### PR TITLE
Updated docs to reflect DayOfWeek Enum order

### PR DESCRIPTION
**Pull request by ghost**
## Summary

The docs had a random order to the days of the week, changed the order to reflect the DayOfWeek enum order.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=4352) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=4352) before we can accept your contribution.<br/><br/>:x: RolandKock95 [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=4352)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-api-docs?pullRequest=4352) it.</sub>

**Comment by RolandKock95** [comment]
FYI, because I moved the order of the items is the Git diff really weird.

**Comment by mairaw** [comment]
Thank you for your contribution @Monksman45. However, this behavior is auto-generated by our reflection tool.
Here's some relevant discussion: 
MicrosoftDocs/feedback#351
MicrosoftDocs/feedback#2028

**Comment by gewarren** [comment]
This has been fixed!

**Pull request closed without merging**
