### PR TITLE
Update to mdoc 5.7.5

### PR DESCRIPTION
**Pull request by joelmartinez**
We've released mdoc 5.7.5 here:  
https://github.com/mono/api-doc-tools/releases/tag/mdoc-5.7.5

copying in the release notes:

- fixing Math.PI value in signatures
- signatures for static constructors
- Supporting multiple FrameworkAlternate values on BaseType 
- Rendering C# Nullable and Tuple types 
- Type forwarding information
- Improving TypeSignature versioning
- Fixing a bug with some EII urls being formatted incorrectly
- F# and VB signatures now supports more scenarios, so previously missing signatures will now be present.
- Tripleslash docs importer now clears existing EcmaXml content before importing 

The bulk of the changes mainly seem to be adding new VB.NET signatures that were previously not added, and adding type forwarding nodes (which document the type forward chains that occur in each moniker). Aside from that, we'll also see some additions of "implements" nodes for some members which previously did not have the link to the interface member it implements.

### CODE REVIEW

**Comment by mairaw** [comment]
Closing because this brings back some unwanted 1.1 APIs. Need to run CI against a different assemblies branch. I’ll make sure both are in sync.

**Comment by joelmartinez** [comment]
@mairaw ok, please ping me when the branch that I should re-run this against

**Comment by mairaw** [comment]
I wanted @BillWagner to test the CI process too. So I'll get that ready and have him run it instead. Is mdoc already on the master branch for the CI process?

**Comment by joelmartinez** [comment]
@mairaw yes, mdoc 5.7.5 is in both the master and working branches of the ReferenceAutomation repo ... so any CI that you run will use that version.

@BillWagner please let me know if I can be of any assistance, or if you want to talk about any of the changes :D

**Pull request closed without merging**
