### PR TITLE
Repaire MSDN url with Docs url

### PR DESCRIPTION
**Pull request by luyajun0205**
## Summary

Repaire MSDN url with Docs url

Fixes AB#222279
https://dev.azure.com/ceapex/Engineering/_workitems/edit/222279

### CODE REVIEW

**Comment by TianqiZhang** [comment]
@BillWagner @mairaw this is part of the effort in [feature 179466](https://dev.azure.com/ceapex/Engineering/_workitems/edit/179466) to fix all MSDN links in `dotnet-api-docs` repo.

We also found several MSDN links that turn out to be error pages, here's a list of them:

Can't repair msdn url https://msdn.microsoft.com/library/ms530302.aspx into file G:\SourceCode\DevCode\dotnet-api-docs\xml\System.Windows.Forms\HtmlElement.xml
Can't repair msdn url https://msdn.microsoft.com/library/ms534312.aspx into file G:\SourceCode\DevCode\dotnet-api-docs\xml\System.Windows.Forms\HtmlElement.xml
Can't repair msdn url https://msdn.microsoft.com/mobile/ into file G:\SourceCode\DevCode\dotnet-api-docs\xml\System.Web.UI.WebControls\AdRotator.xml
Can't repair msdn url https://msdn.microsoft.com/mobility/ into file G:\SourceCode\DevCode\dotnet-api-docs\xml\System.Web.UI.WebControls\AdRotator.xml
Can't repair msdn url https://msdn.microsoft.com/library/ms794597.aspx into file G:\SourceCode\DevCode\dotnet-api-docs\xml\System.Windows.Media\ColorContext.xml
Can't repair msdn url https://msdn.microsoft.com/library/82f7fc69-808c-40ff-a23f-ee3fb8dbd9e2 into file G:\SourceCode\DevCode\dotnet-api-docs\xml\System.Data.Metadata.Edm\ComplexType.xml

**Comment by mairaw** [comment]
I've explained in the task why I think doing a global search and replace is not ideal here. But I'll let the @dotnet/docs decide what they wanna do here. I was planning to continue to submit my PRs to replace these links in this repo.

**Comment by IEvangelist** [comment]
Based on reading through the comments on [Azure DevOps #222279](https://dev.azure.com/ceapex/Engineering/_workitems/edit/222279) from @mairaw - I'm inclined to agree with her. We should really be ensuring that each link is the most appropriate URL to use. Is there anyway to batch these in smaller PRs so that they are easier to review?

**Comment by BillWagner** [comment]
I agree with both @mairaw and @IEvangelist 

At a minimum, we need to see these changes in smaller batches to review them more carefully.

**Comment by TianqiZhang** [comment]
@mairaw @BillWagner  @IEvangelist sounds good, then we will make the following changes to our tool and to how we open PRs:
- If the redirected link starts with "/previous-versions/" or contains "?view=xxx", we won't replace them.
- We will batch the changes to 100 files per PR, and we will only open the next PR after the previous one is merged.

What do you think?

**Comment by mairaw** [comment]
I think that's a good plan @TianqiZhang.

**Comment by luyajun0205** [comment]
So can I close this PR firstly? I will send a small PR with 100 files change later.

**Comment by IEvangelist** [comment]
> So can I close this PR firstly? I will send a small PR with 100 files change later.

Yes, you can close this PR.

**Pull request closed without merging**
