### PR TITLE
Fixed docs for ExtractToDirectory(..., bool overwriteFiles) overloads

### LINKED ISSUE #5483: ZipFile.ExtractToDirectory(string, string, bool) incorrectly states destination directory cannot exists
---
**Issue moved from dotnet/docs#23513**
- Please respond to @UpperAvenue.

---

_From @UpperAvenue on Friday, March 26, 2021 8:14:46 PM_

**Issue description**

[ZipFile.ExtractToDirectory(string, string, bool) documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectory?view=net-5.0#System_IO_Compression_ZipFile_ExtractToDirectory_System_String_System_String_System_Boolean_)

Documentation states the destination directory specified must not exist, but that is not true if the *overwriteFiles* parameter is set to true.  This is incorrectly stated in the Parameter documentation the Exceptions documentation and the Remarks documentation.

(I have not verified the other parts of the documentation, only the part that says the destination directory must not exists.)

**Target framework**

.NET 5

### PR DESCRIPTION
**Pull request by UpperAvenue**
## Summary

- Changed IOException to state that it is only thrown if overwriteFiles is false and the specified directory does not exist.
- Changed the remarks to reflect that change.  
- Removed statement in the description for the destinationDirectoryName param that said directory must exist.
- Specified in remarks that both sourceArchiveFileName and destinationDirectoryName param accept relative and absolute paths.

Fixes #5483

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=6675) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=6675) before we can accept your contribution.<br/><br/>:x: UpperAvenue [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=6675)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-api-docs?pullRequest=6675) it.</sub>

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @UpperAvenue !

**Comment by adamsitnik** [comment]
@UpperAvenue could you please sign the Contributor License Agreement https://github.com/dotnet/dotnet-api-docs/pull/6675#issuecomment-828576713 ?

**Comment by gewarren** [comment]
Ping @UpperAvenue

**Pull request merged**
