### PR TITLE
remove redundant assembly versions from ECMAXML

### PR DESCRIPTION
**Pull request by TianqiZhang**
## Summary

By default mdoc won't clean up history assembly versions if we update an assembly in binaries repo. This results in many redundant assembly version nodes in ECMAXML files. This PR removes them.

### CODE REVIEW

**Comment by gewarren** [comment]
@TianqiZhang Thank you for cleaning this up. How did you know/decide which assembly versions to remove?

**Comment by TianqiZhang** [comment]
@gewarren I wrote a small program to compare assembly verisons in ECMAXML with the versions in framework index files. FrameworkIndex files get overwritten every time mdoc runs, so the versions in it are up-to-date. For versions in ECMAXML though, mdoc does only appending, so some legacy versions remains. //cc @joelmartinez 

Here 's the source code of the small tool I put together:
```csharp
   class Program
    {
        static void Main(string[] args)
        {
            var rootFolder = "E:\\mdoc\\azure-docs-sdk-dotnet\\xml";
            var frameworkIndexFolder = Path.Combine(rootFolder, "FrameworksIndex");
            Regex asmRegex = new Regex("<Assembly Name=\"([\\w.]*)\" Version=\"([\\d.]*)\" \\/>", RegexOptions.Compiled | RegexOptions.Multiline);
            List<(string, string)> allAsmList = new List<(string, string)>();
            foreach(var frameworkIndexFile in Directory.GetFiles(frameworkIndexFolder, "*.xml"))
            {
                var text = File.ReadAllText(frameworkIndexFile);
                foreach(Match match in asmRegex.Matches(text))
                {
                    allAsmList.Add((match.Groups[1].ToString(), match.Groups[2].ToString()));
                }
            }

            var asmLookup = allAsmList.ToLookup(a => a.Item1);
            Regex asmNameRegex = new Regex("<AssemblyName>([\\w.]*)<\\/AssemblyName>", RegexOptions.Compiled);
            Regex asmVersionRegex = new Regex("<AssemblyVersion>([\\d.]*)<\\/AssemblyVersion>", RegexOptions.Compiled);
            foreach (var xmlFile in Directory.GetFiles(rootFolder, "*.xml", SearchOption.AllDirectories)
                .Where(f => !f.Contains("FrameworksIndex")))
            {
                var lines = File.ReadAllLines(xmlFile);
                var processedLines = new List<string>();
                string currentAsm = null;
                foreach(var line in lines)
                {
                    if (currentAsm == null)
                    {
                        processedLines.Add(line);
                    }
                    else if (line.EndsWith("</AssemblyInfo>"))
                    {
                        currentAsm = null;
                        processedLines.Add(line);
                    }
                    if (currentAsm != null)
                    {
                        var versionMatch = asmVersionRegex.Match(line);
                        if (versionMatch?.Success == true)
                        {
                            var version = versionMatch.Groups[1].Value;
                            if (asmLookup[currentAsm].Any(t => t.Item2 == version))
                            {
                                processedLines.Add(line);
                            }
                            continue;
                        }
                    }
                    var nameMatch = asmNameRegex.Match(line);
                    if (nameMatch?.Success == true)
                    {
                        currentAsm = nameMatch.Groups[1].Value;
                        continue;
                    }
                }
                if (processedLines.Count < lines.Count())
                {
                    File.WriteAllLines(xmlFile, processedLines);
                }
            }
        }
    }
```

**Comment by AaronRobinsonMSFT** [comment]
`System.Runtime.InteropServices.*` LGTM.

**Review by gewarren — APPROVED** [review]

**Comment by gewarren** [comment]
Thank you @TianqiZhang

**Pull request merged**
