### PR TITLE
Try .NET -- String.xml -- re-adding interactivity to sample refs

### PR DESCRIPTION
**Pull request by WilliamAntonRohm**
### (this PR has been superseded by the currently mergeable #3773)

Updated this minute's version of String.xml to include all interactive samples

Waiting on this build to double-check placement of interactive Notes

### CODE REVIEW

**Comment by mairaw** [comment]
Replaces #2971 correct?

**Comment by WilliamAntonRohm** [comment]
Yes -- this one (3458) is the "real" String.xml PR

**Comment by mairaw** [comment]
Need a fresh build

**Comment by WilliamAntonRohm** [comment]
@mairaw -- Maira, please review these changes.

**Comment by mairaw** [comment]
@WilliamAntonRohm can you resolve the conflicts here and also remove any references to the include notes? Thanks.

**Comment by WilliamAntonRohm** [comment]
@mairaw -- Maira, I've re-added just the -interactive samples into a new replacement PR #3773 which is currently mergeable.

**Pull request closed without merging**
