### PR TITLE
Update live with current master

### PR DESCRIPTION
**Pull request by mairaw**

### CODE REVIEW

**Comment by mairaw** [comment]
@carlossanlop is JsonNode a new API in .NET 5?

**Comment by carlossanlop** [comment]
>  is JsonNode a new API in .NET 5?

@AhsonKhan @Jozkee @layomia @steveharter can you answer this question?

**Comment by ericstj** [comment]
JsonNode is new in 5.0.  It's the result of the writeable DOM project.  https://github.com/dotnet/runtime/issues/30436
It's API that is still  in flux, so we shouldn't invest in documenting it a ton yet.

**Comment by carlossanlop** [comment]
@ericstj thanks for your answer. The comment got merged before area owners could confirm if it was shipped or not. Should I remove it?

**Comment by carlossanlop** [comment]
It's probably not that bad to keep the comment, considering the whole file has already been documented: https://github.com/dotnet/dotnet-api-docs/pull/3945/files

But I'll let the area owners confirm this. 

@ahsonkhan @Jozkee @steveharter @layomia in case they have a different opinion and would like me to revert it.

**Comment by ahsonkhan** [comment]
We should remove it until its shipped in preview. We don't want docs to be published when the API isn't ready.

**Pull request merged**
