### PR TITLE
Fixes exception info

### LINKED ISSUE #3396: Incorrect FileNotFoundException in Process.Start(ProcessStartInfo)
A `Win32Exception` is throw if the file could not be found, on both Windows and Linux.

### PR DESCRIPTION
**Pull request by mairaw**
Fixes #3396

### CODE REVIEW

**Comment by mairaw** [comment]
@wtgodbe, @krwq can you please review? Also, is it expected that customers would get a Win32Exception on a Linux machine or should I create a bug for corefx on this?

**Comment by NextTurn** [comment]
@mairaw You could also revise exception info in other overloads because they are similar.

**Comment by mairaw** [comment]
Which ones @NextTurn? When I looked, the other overloads returning FileNotFound talked about quotes in the PATH env var. Are you saying those are also not correct?

**Comment by NextTurn** [comment]
Sorry for the confusion @mairaw. I meant the Win32Exception in other overloads.

Is "file could not be found" considered one of the "errors occurred when opening the associated file"?

**Comment by mairaw** [comment]
Ah gotcha! I'd have to do some more testing.

**Comment by mairaw** [comment]
@NextTurn I'll merge this one so we're not blocked. Can you open another issue for the other overloads?

**Pull request merged**
