### PR TITLE
Link to diagnostic IDs

### PR DESCRIPTION
**Pull request by terrajobst**
This links to the topic added in https://github.com/dotnet/docs/pull/37877.

### CODE REVIEW

**Comment by gewarren** [comment]
Thank you @terrajobst

**Comment by BillWagner** [comment]
closing and reopening for a fresh build.

**Comment by terrajobst** [comment]
@BillWagner @gewarren any idea how to fix the links? They point to conceptual docs in the dotnet/docs repo.

**Comment by gewarren** [comment]
> @BillWagner @gewarren any idea how to fix the links? They point to conceptual docs in the dotnet/docs repo.

They're correct as-is. The most recent commit is still building.

**Pull request merged**
