### PR TITLE
Update docs from trippleslash comments

### PR DESCRIPTION
**Pull request by rzikm**
## Summary

Update missing documentation. Fixes https://github.com/dotnet/runtime/issues/74732.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM

**Review by gewarren — APPROVED** [review]

**Comment by rzikm** [comment]
@gewarren sorry, I enabled auto merge and missed your comments, I will post a follow-up PR

**Comment by gewarren** [comment]
No worries, thank you!

**Comment by carlossanlop** [comment]
@rzikm do you mind applying the suggestions directly into the triple slash, before submitting the follow up PR here? The runtime PR still has some open comments to address.

**Pull request merged**
