### PR TITLE
Fix grammar in comment 

### PR DESCRIPTION
**Pull request by ylorph**
Fix grammar in comment

### CODE REVIEW

**Review by buyaa-n — APPROVED** [review]

**Comment by buyaa-n** [comment]
Thanks for your fix @ylorph, now code samples require a project file, could you add a project file like [this ](https://github.com/dotnet/dotnet-api-docs/blob/main/samples/snippets/csharp/VS_Snippets_Remoting/ClassicTcpClient.PublicMethodsAndPropertiesExample/CS/TcpClient.csproj) in the same folder?

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=7586) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=7586) before we can accept your contribution.<br/><br/>:x: ylorph [sign now](https://cla.dotnetfoundation.org/dotnet/dotnet-api-docs?pullRequest=7586)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotnet-api-docs?pullRequest=7586) it.</sub>

**Comment by ylorph** [comment]
@buyaa-n I've added the project file .

**Review by gewarren — APPROVED** [review]
Thank you @ylorph

**Pull request merged**
