### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by v-alje**
Build.Reason:Manual by Alma Jenks
 Build.Url:https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=222466&view=results
 source_repo.branch:release-msbuild
 source_repo.url:https://apidrop.visualstudio.com/_git/binaries

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by ghogen** [comment]
@v-alje Is it because the smoke-test branch is out-of-date with the base branch - I'm seeing that warning on the PR.

**Comment by v-alje** [comment]
@ghogen No, that is because there have been changes merged to main since this branch was created. They shouldn't have anything to do with reference generation.

**Comment by ghogen** [comment]
@gewarren @v-alje Apart from the FrameworksIndex files that were not expected to change, the warnings about missing cross-links would appear to be an issue in the MSBuild source code, since we are now pulling the docs from MSBuild NuGet packages. What is the normal practice for such cases. We can file bugs against MSBuild for those fixes, but that would not be reflected in the 16.10 NuGet packages.

**Comment by gewarren** [comment]
I'm confused about the FrameworksIndex changes too. I'm glad to see that the number of changed files is way lower in this PR, but it's still best to probably exclude anything but the Microsoft.Build.* and ns-Microsoft.Build* files from this PR.

**Comment by v-alje** [comment]
@gewarren @ghogen Okay, I have copied the MSBuild changes to the release-msbuild16 branch and will close this pull request, and we can work there.

**Pull request closed without merging**
