### PR TITLE
Update BaseDirectory Snippets

### PR DESCRIPTION
**Pull request by philipwolfe**
## Summary

I think using Path.Combine is a better practice that string concatenation.

### CODE REVIEW

**Comment by BillWagner** [comment]
Hi @philipwolfe 

Right now, the sample build is failing. I've reviewed the changes, and I agree with what you've added.

Can you add a project file (csproj / vbproj) in each folder? Then, our CI build will pass the sample, and we'll :shipit:

**Comment by philipwolfe** [comment]
yep, give me just a bit.  Probably over the weekend.

**Comment by philipwolfe** [comment]
Hi @BillWagner,
I added a csproj for the C# snippets and fixed the build errors for that folder.  For the VB code, the folder that made the most sense for a .vbproj file is VS_Snippets_CLR.  When I added a vbproj file at that location, there were 896 files with errors.  I thought that would be a bit to much to fix for this PR.  Probably need to decide if those folders should be split out more and/or how much maintenance time should be given to them with portions of the CLR changing from netfx 4.8 to .net 6/7.  (I am still dealing with appdomains and migrating to alternatives.)
pw

**Review by BillWagner — APPROVED** [review]
This LGTM @philipwolfe 

I'll :shipit: now.

**Comment by BillWagner** [comment]
closing and reopening for a fresh build

**Pull request merged**
