### PR TITLE
Added useful details to `PipeStream.ReadMode`

### PR DESCRIPTION
**Pull request by peteraritchie**
## Summary

Added some details to `ReadMode` with regard to implicit calls to `InitializeHandle` and exceptions before `NamedPipeClientStream.Connect` is called.

### CODE REVIEW

**Comment by BillWagner** [comment]
Can you review this @JeremyKuhne 

Thank you.

**Comment by rpetrusha** [comment]
Thanks, @peteraritchie, for submitting your PR. The exception, though, is documented in the Exceptions section, and of the four types derived from NamedPipeClientStream, only the NamedPipeClientStream type has a Connect method. A generalized alternative is to retrieve the value of the PipeStream.IsConnected property before accessing the ReadMode property. 

Thoughts, @jeremykuhne and @peteraritchie.

**Comment by JeremyKuhne** [comment]
A number of properties throw if the handle hasn't been set up or if the class has been disposed. `NamedPipeClientStream` also throws when accessing properties if the connection isn't active. Not having a handle set up isn't something that happens outside of the NamedPipeClientStream as it gets set up in the constructors in the other classes.

As @rpetrusha points out, it is already documented that this throws in this way. I'm fine with calling out how to check if `NamedPipeClientStream` is connected.

**Comment by peteraritchie** [comment]
Thanks for the feedback @rpetrusha.  As you say only NamedPipeClientStream has a Connect method--which makes IsConnected not as obvious.  I think the root of the issue is the opportunity to improve the inheritance hierarchy (if the opportunity for that level of change was there) and thus make PipeStream ReadMode more clear in the unique conditions of the inheritors.  Lacking that, it makes simply inheriting the documentation less than clear.  The message "handle not created" isn't clear when using a specialization of PipeStream that hides that implementation detail.  e.g. what you need to do to avoid the exception with ReadMode depends on the specialization and thus the PipeStream.ReadMode documentation becomes awkward because of it.
I suspect that details of that arguable Liskov violation isn't enough to do the same in the documentation (two wrongs don't make it right); so, I've updated the PR to focus on IsConnected to avoid the exception.

**Comment by rpetrusha** [comment]
Closing and reopening to trigger a new CLA check.

**Pull request merged**
