### PR TITLE
Remove unneeded sentences

### PR DESCRIPTION
**Pull request by nxtn**
Continued from #1735

### CODE REVIEW

**Comment by NextTurn** [comment]
These sentences should appear before incomplete examples, but these are all complete ones with namespaces imported.

**Comment by mairaw** [comment]
I agree but at least on the [first example](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.printing.querypagesettingseventargs?view=netframework-4.7.2) that I opened the example is not complete and it doesn't show the using statements:
image

They're helpful in this scenario, no?

**Comment by NextTurn** [comment]
It was the only mistake. Sorry for that.

**Comment by NextTurn** [comment]
All checked.

There must be a lot of incomplete examples without namespace hints. We could create a new issue to track these.

**Comment by NextTurn** [comment]
I suggest to include the whole file for examples like [this](https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR_System/system.Reflection.Emit.ILGenerator.EmitCalli%20Example/CS/source.cs), otherwise the readers will be confused about the parameter/field types.

**Comment by mairaw** [comment]
I agree that we can either expand samples or include namespace hints. That's a massive task and not something we can take on right now. But feel free to open an issue to track this and will gladly accept community contributions with such changes. 

So closing this one based on what you said earlier that was a mistake in this particular PR.

**Comment by NextTurn** [comment]
@mairaw I meant the removal in [QueryPageSettingsEventArgs Class](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.printing.querypagesettingseventargs?view=netframework-4.7.2) was a mistake. Others are OK.

**Pull request closed without merging**
