### PR TITLE
System.Double F# snippets

### PR DESCRIPTION
**Pull request by albert-du**
Adds F# snippets for Double

### CODE REVIEW

**Comment by albert-du** [comment]
@dsyme Could you review?

**Review by BillWagner — COMMENTED** [review]
This also all LGTM @albert-du 

Commening so this stays in my queue. 

I'll merge once @dsyme has had a look.

**Review by dsyme — APPROVED** [review]

**Comment by albert-du** [comment]
@BillWagner this is ready

**Review by BillWagner — APPROVED** [review]
Thanks again @albert-du 

I'll :shipit: now

**Pull request merged**
