### PR TITLE
Improve numeric types

### PR DESCRIPTION
**Pull request by gewarren**
- Add see also links to numeric format string articles from `TryFormat` methods
- Replace ".NET Framework" with ".NET" where appropriate

### CODE REVIEW

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

You can :shipit: when ready.

**Comment by pgovind** [comment]
Just got around to seeing this. I know this is merge already, but this LGTM!

**Comment by gewarren** [comment]
> Just got around to seeing this. I know this is merge already, but this LGTM!

@pgovind Thanks for checking it!

**Comment by gewarren** [comment]
@carlossanlop I guess this PR isn't any good since these comments were already backported. Should I just manually update dotnet/runtime with these changes?

**Pull request merged**
