### PR TITLE
Port System.Reflection.Metadata source code comments to Docs (F-I files)

### PR DESCRIPTION
**Pull request by carlossanlop**
## Summary

Automatically ported triple slash source code comments found in System.Reflection.Metadata that were not yet documented in dotnet-api-docs.

This PR contains changes to filenames starting with F-I.

Fixes #Issue_Number (if available)

### CODE REVIEW

**Comment by carlossanlop** [comment]
@mairaw @rpetrusha please take a look whenever possible.

Adding the area owners @tmat, @nguerrera in case they have any suggestions or remarks about these changes.

**Comment by carlossanlop** [comment]
@mairaw @rpetrusha if this looks good, can we get it merged?

**Comment by carlossanlop** [comment]
@rpetrusha I addressed your changes. Thank you very much for your new additions. If the build passes, can you please merge this?

**Comment by rpetrusha** [comment]
Thanks for making the additional changes, @carlossanlop. I'll merge your PR now.

**Pull request merged**
