### PR TITLE
Clarify behavior of OfType() with null values

### PR DESCRIPTION
**Pull request by matthiaslischka**
`OfType<T>` does not take all elements that *can be cast*. It skips `null`.
And consequently the hint that `Cast<T>` would *instead* throw is a bit misleading too.

```c#
new List<string> {"Mango", null, "Orange"}.OfType<string>();
// --> ["Mango", "Orange"]
	
new List<string> {"Mango", null, "Orange"}.Cast<string>();
// --> ["Mango", null, "Orange"]
```

BR Matthias

### CODE REVIEW

**Comment by BillWagner** [comment]
ping @KathleenDollard

**Comment by matthiaslischka** [comment]
Any updates on that? Not sure what's up with the Snippets 5000 check - not related to the change.

**Comment by BillWagner** [comment]
closing and reopening for a fresh build (I Think the out-of-support versions have been addressed)

**Comment by BillWagner** [comment]
Hi @matthiaslischka 

I looked everything over. I'll approve the changes once we have a clean build. 

The issue with the snippets build is that it's using `netcoreapp2.2`, which is out of support. Can you update that to `net6.0`? These samples would still compile, and then I'll merge it.

**Review by gewarren — APPROVED** [review]

**Pull request merged**
