### PR TITLE
ReadOnlySpan minor change to wording

### PR DESCRIPTION
**Pull request by Thraka**
## Summary

Reworded `value types` with `instances` per conversation in #358

### CODE REVIEW

**Comment by Thraka** [comment]
@ahsonkhan circled back on this per your feedback. Please approve :) thanks!!

**Comment by ahsonkhan** [comment]
What about this comment? https://github.com/dotnet/dotnet-api-docs/pull/358#discussion_r205549552

https://github.com/dotnet/dotnet-api-docs/blob/865601cc851c260d00de82e6708dd2edf7248d72/xml/System/ReadOnlySpan%601.xml#L730

**I think we should re-write it as follows:**
It it sometimes necessary when APIs that support `<xref:System.ReadOnlySpan%601>` are not available, but APIs that work with arrays are.

**Comment by Thraka** [comment]
@ahsonkhan I think you need to approve it

**Comment by ahsonkhan** [comment]
> I think you need to approve it

I did. But will do it again :)

**Comment by ahsonkhan** [comment]
> At least 1 approving review is required by reviewers with write access. 

I don't have write access. So probably usual repo contributors will need to review and approve.

**Comment by BillWagner** [comment]
> I don't have write access. So probably usual repo contributors will need to review and approve.

I'm on it.  Thanks for approving @ahsonkhan That helps me know the content is technically accurate.

**Pull request merged**
