### PR TITLE
Automatically port System.Diagnostics triple slash comments

### PR DESCRIPTION
**Pull request by carlossanlop**
Found an additional batch of triple slash comments that can be ported.

### CODE REVIEW

**Comment by carlossanlop** [comment]
Adding area owners: @wtgodbe, @krwq
Adding language reviewers: @mairaw @rpetrusha

**Comment by krwq** [comment]
Curious, are we going to merge back the xml into comments (if there is any mismatch)?

**Comment by rpetrusha** [comment]
No. We've never merged documentation updates back into triple-slash comments, @krwq.

**Comment by carlossanlop** [comment]
@krwq it's not in our current plans to port back the comments to triple slash.
The triple slash comments are going to be used for seeding, but after that, MS Docs will be considered the source of truth.
Maybe in the future we can have the conversation: we could port them back, or just delete triple slash comments completely.

**Comment by rpetrusha** [comment]
I've made revisions through the Activities, SpanId property, @carlossanlop. I'll finish them tomorrow morning.

**Comment by carlossanlop** [comment]
@rpetrusha looks good, thank you.

**Comment by rpetrusha** [comment]
This looks good, so I'll approve and merge now, @carlossanlop.

**Pull request merged**
