### PR TITLE
Add 2 OOB .NET extension assemblies

### PR DESCRIPTION
**Pull request by gewarren**
Adds System.Memory.Data.dll and System.ServiceModel.Federation.dll APIs to .NET Core 2.0+ extensions.

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by gewarren** [comment]
This is what the ["Applies to" section](https://review.docs.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-2.0&branch=pr-en-us-5128#moniker-applies-to) looks like for BinaryData. It doesn't mention .NET Standard. Is this okay?

image

**Comment by safern** [comment]
> It doesn't mention .NET Standard. Is this okay?

I think this is how it shows for others, right? Or do we have a .NET Standard Platform Extensions moniker as well?

**Comment by jeffhandley** [comment]
I noticed "To be added" throughout the docs. Does this step add the type/member definitions for the docs to get inserted to after a subsequent step?

**Comment by gewarren** [comment]
> I think this is how it shows for others, right? Or do we have a .NET Standard Platform Extensions moniker as well?

We don't currently have a .NET Standard Platform Extensions moniker. Maira suggested we ask @terrajobst about whether we should have such a moniker.

> I noticed "To be added" throughout the docs. Does this step add the type/member definitions for the docs to get inserted to after a subsequent step?

Yes, since we didn't import doc comments for this PR, Carlos will bring them over in a subsequent step. This was intentional so as not to overwrite docs for other APIs.

**Comment by gewarren** [comment]
I'll go ahead and merge this. If we decide to add a .NET Standard Platform Extensions moniker, we can add this to it later.

**Comment by terrajobst** [comment]
Makes sense. Thanks!

**Pull request merged**
