### PR TITLE
Updated HttpUtility ParseQueryString code snippets for C# and VB

### LINKED ISSUE #9251: Improve HttpUtility.ParseQueryString formatting and code snipped for C#
Hi all!

I checked the [`HttpUtility.ParseQueryString`](https://learn.microsoft.com/en-us/dotnet/api/system.web.httputility.parsequerystring?view=net-7.0) method documentation and I realized that some of the formatting and variable naming could be greatly improved.

I could create a pull request and change these things if that's okay.

image

### PR DESCRIPTION
**Pull request by JoanGil**
## Summary

Fixes #9251

This pull request enhances the C# and VB language examples on the [HttpUtility.ParseQueryString](https://learn.microsoft.com/en-us/dotnet/api/system.web.httputility.parsequerystring?view=net-7.0) page. Following a discussion with @MichaelDeutschCoding, I've introduced two updated versions of the code to replace the outdated examples that did not adhere to clean code principles.

Thanks  @gewarren and @carlossanlop for guiding me!

### CODE REVIEW

**Comment by JoanGil** [comment]
@dotnet-policy-service agree

**Comment by JoanGil** [comment]
Hi @Rick-Anderson! Any news on this one?

**Comment by Rick-Anderson** [comment]
File

Status

Preview URL

ms.author

ms.prod

ms.technology

ms.service

ms.subservice

Details

[snippets/csharp/VS_Snippets_WebNet/HttpUtility_ParseQueryString/cs/httputility_parsequerystring.aspx](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/snippets/csharp/VS_Snippets_WebNet/HttpUtility_ParseQueryString/cs/httputility_parsequerystring.aspx)	Succeeded	n/a (file deleted or renamed)						
[snippets/csharp/VS_Snippets_WebNet/HttpUtility_ParseQueryString/cs/httputility_parsequerystring.cs](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/snippets/csharp/VS_Snippets_WebNet/HttpUtility_ParseQueryString/cs/httputility_parsequerystring.cs)	Succeeded	[View](https://review.learn.microsoft.com/en-us/dotnet/api/system.web.httputility?view=net-8.0&branch=pr-en-us-9342)						
[snippets/visualbasic/VS_Snippets_WebNet/HttpUtility_ParseQueryString/vb/httputility_parsequerystring.aspx](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/snippets/visualbasic/VS_Snippets_WebNet/HttpUtility_ParseQueryString/vb/httputility_parsequerystring.aspx)	Succeeded	n/a (file deleted or renamed)						
[snippets/visualbasic/VS_Snippets_WebNet/HttpUtility_ParseQueryString/vb/httputility_parsequerystring.vb](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/snippets/visualbasic/VS_Snippets_WebNet/HttpUtility_ParseQueryString/vb/httputility_parsequerystring.vb)	Succeeded	[View](https://review.learn.microsoft.com/en-us/dotnet/api/system.web.httputility?view=net-8.0&branch=pr-en-us-9342)						
[xml/System.Web/HttpUtility.xml](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/xml/System.Web/HttpUtility.xml)	Succeeded	[View](https://review.learn.microsoft.com/en-us/dotnet/api/system.web.httputility?view=net-8.0&branch=pr-en-us-9342)

**Comment by JoanGil** [comment]
> File
> 
> Status
> 
> Preview URL
> 
> ms.author
> 
> ms.prod
> 
> ms.technology
> 
> ms.service
> 
> ms.subservice
> 
> Details
> 
> [snippets/csharp/VS_Snippets_WebNet/HttpUtility_ParseQueryString/cs/httputility_parsequerystring.aspx](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/snippets/csharp/VS_Snippets_WebNet/HttpUtility_ParseQueryString/cs/httputility_parsequerystring.aspx) Succeeded n/a (file deleted or renamed) [snippets/csharp/VS_Snippets_WebNet/HttpUtility_ParseQueryString/cs/httputility_parsequerystring.cs](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/snippets/csharp/VS_Snippets_WebNet/HttpUtility_ParseQueryString/cs/httputility_parsequerystring.cs) Succeeded [View](https://review.learn.microsoft.com/en-us/dotnet/api/system.web.httputility?view=net-8.0&branch=pr-en-us-9342) [snippets/visualbasic/VS_Snippets_WebNet/HttpUtility_ParseQueryString/vb/httputility_parsequerystring.aspx](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/snippets/visualbasic/VS_Snippets_WebNet/HttpUtility_ParseQueryString/vb/httputility_parsequerystring.aspx) Succeeded n/a (file deleted or renamed) [snippets/visualbasic/VS_Snippets_WebNet/HttpUtility_ParseQueryString/vb/httputility_parsequerystring.vb](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/snippets/visualbasic/VS_Snippets_WebNet/HttpUtility_ParseQueryString/vb/httputility_parsequerystring.vb) Succeeded [View](https://review.learn.microsoft.com/en-us/dotnet/api/system.web.httputility?view=net-8.0&branch=pr-en-us-9342) [xml/System.Web/HttpUtility.xml](https://github.com/JoanGil/dotnet-api-docs/blob/improve-http-utility-code-snippets/xml/System.Web/HttpUtility.xml) Succeeded [View](https://review.learn.microsoft.com/en-us/dotnet/api/system.web.httputility?view=net-8.0&branch=pr-en-us-9342)

Is this something that I have to solve? Everything seems to be success and I don't have access to most of the files. Anything I can do?

**Comment by carlossanlop** [comment]
Sorry for the late response.

@gewarren is the main contact for this repo, she can help review. @Rick-Anderson since you own System.Web, can you also please take a look?

> Is this something that I have to solve? Everything seems to be success and I don't have access to most of the files. Anything I can do?

The CI passed, those are succeeded validation results, you don't need to do anything else for now. This now needs a code review.

**Comment by gewarren** [comment]
@JoanGil The Try.NET snippet fails with these errors when I preview it in the browser (you won't have permissions to do that unfortunately):

program.cs(4,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
program.cs(4,5): error CS0116: A namespace cannot directly contain members such as fields or methods
program.cs(5,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
program.cs(5,5): error CS0116: A namespace cannot directly contain members such as fields or methods
program.cs(5,17): error CS0103: The name 'url' does not exist in the current context
program.cs(8,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
program.cs(8,53): error CS0103: The name 'parsedUrl' does not exist in the current context
program.cs(11,1): error CS1022: Type or namespace definition, or end-of-file expected
program.cs(11,17): error CS8124: Tuple must contain at least two elements.
program.cs(11,17): error CS1026: ) expected
program.cs(11,17): error CS1022: Type or namespace definition, or end-of-file expected
program.cs(11,37): error CS0116: A namespace cannot directly contain members such as fields or methods
program.cs(11,44): error CS1022: Type or namespace definition, or end-of-file expected
program.cs(13,13): error CS0116: A namespace cannot directly contain members such as fields or methods
program.cs(13,23): error CS1031: Type expected
program.cs(13,23): error CS8124: Tuple must contain at least two elements.
program.cs(13,23): error CS1026: ) expected
program.cs(13,23): error CS1022: Type or namespace definition, or end-of-file expected
program.cs(14,1): error CS1022: Type or namespace definition, or end-of-file expected

**Comment by JoanGil** [comment]
> @JoanGil The Try.NET snippet fails with these errors when I preview it in the browser (you won't have permissions to do that unfortunately):
> 
> program.cs(4,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code program.cs(4,5): error CS0116: A namespace cannot directly contain members such as fields or methods program.cs(5,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code program.cs(5,5): error CS0116: A namespace cannot directly contain members such as fields or methods program.cs(5,17): error CS0103: The name 'url' does not exist in the current context program.cs(8,1): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code program.cs(8,53): error CS0103: The name 'parsedUrl' does not exist in the current context program.cs(11,1): error CS1022: Type or namespace definition, or end-of-file expected program.cs(11,17): error CS8124: Tuple must contain at least two elements. program.cs(11,17): error CS1026: ) expected program.cs(11,17): error CS1022: Type or namespace definition, or end-of-file expected program.cs(11,37): error CS0116: A namespace cannot directly contain members such as fields or methods program.cs(11,44): error CS1022: Type or namespace definition, or end-of-file expected program.cs(13,13): error CS0116: A namespace cannot directly contain members such as fields or methods program.cs(13,23): error CS1031: Type expected program.cs(13,23): error CS8124: Tuple must contain at least two elements. program.cs(13,23): error CS1026: ) expected program.cs(13,23): error CS1022: Type or namespace definition, or end-of-file expected program.cs(14,1): error CS1022: Type or namespace definition, or end-of-file expected

Okay, I have updated the code, wrapping it inside a Program and Main. Hopefully this will solve the C# problems. Could you check again @gewarren. Thanks!

**Review by gewarren — APPROVED** [review]
It works now; thanks @JoanGil!

**Pull request merged**
