### PR TITLE
Switch msdn link to /docs/standard/events/index.md

### PR DESCRIPTION
**Pull request by ChrisMaddock**
Relates to https://github.com/dotnet/docs/issues/2037

I built on the code from https://github.com/dotnet/docs/issues/2037 to find links that don't point directly to docs, but redirect there. (So, mostly msdn and fwlinks.)

This is the second-most prolific in this repo - this PR just changes 449 references to http://msdn.microsoft.com/library/b6f65241-e0ad-4590-a99f-200ce741bb1f to point directly to https://docs.microsoft.com/en-us/dotnet/standard/events/index.

I didn't split this PR up as it's only the one link - let me know if it would be easier if I had done!

### CODE REVIEW

**Comment by mairaw** [comment]
Thanks @ChrisMaddock! The size of the PR is fine. 

I think the build will probably fail because of the missing ~. Take a look at a similar PR that I've addressed the same issue: https://github.com/dotnet/dotnet-api-docs/pull/69/files

**Comment by ChrisMaddock** [comment]
Ah, sorry! I thought tilde's were [out of fashion](https://github.com/dotnet/docs/pull/4119#issuecomment-358124204)! Did that change with the repo split? 

Updated. 😄

**Comment by mairaw** [comment]
For API reference, we always had to use the ~ when linking to topics on dotnet/docs. For conceptual, we still try to avoid that. Apologies for some of this confusing guidance.

**Comment by ChrisMaddock** [comment]
Haha, thanks! So long as it's correct in the end! 😄

**Pull request merged**
