### PR TITLE
Some finalizers instead destructors

### PR DESCRIPTION
**Pull request by deep-outcome**
## Summary

Replacements for _destructor_ with _finalizer_ for C#.

### CODE REVIEW

**Review by tannergooding — APPROVED** [review]
LGTM. As per https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors, `finalizer` is the current term and `destructor` is the "historical" term.

**Review by BillWagner — APPROVED** [review]
This LGTM @Uzivatel919 

I'll :shipit: now.

**Comment by BillWagner** [comment]
@Uzivatel919 I spoke too soon approving this. The "Snippets 5000" builds all the snippet projects that contain code included in the API docs. For historical reasons, older snippets don't have a project file and therefore don't build.

Before we merge this, can you add a .csproj file in each of the folders with samples. Once those build cleanly, we'll merge this.

(Historically, the samples were stored in an internal tool, and builds were done on checkin. We've added back a similar function in our open source model now.)

**Comment by Uzivatel919** [comment]
@BillWagner, csprojs there.

**Review by BillWagner — APPROVED** [review]
Thanks @Uzivatel919 

I'll :shipit: now.

**Pull request merged**
