### PR TITLE
Updating docs for release 6.0

### PR DESCRIPTION
**Pull request by dreddy-work**
## Summary

Updating Docs for release 6.0 from the source ( from triple slash comments)

Fixes #5167

### CODE REVIEW

**Comment by dreddy-work** [comment]
@carlossanlop as FYI.

**Comment by dreddy-work** [comment]
related https://github.com/dotnet/dotnet-api-docs/pull/6940

**Review by carlossanlop — CHANGES_REQUESTED** [review]
This PR is deleting files manually, which is not the correct way of documenting APIs. The process is automated by the Docs build system when we feed it with the latest ref assemblies.

**Comment by dreddy-work** [comment]
closing in response to https://github.com/dotnet/dotnet-api-docs/pull/7114

**Pull request closed without merging**
